import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
const built=await build({stdin:{contents:'export {CorporateWorkflows} from "./src/corporate-workflow.ts";',resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false});const {CorporateWorkflows}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
test('Shared workflow binds consent and reviewed output, recovers lost response, and never restores revoked access',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v))};
 const content='{"private-source":"sentinel"}',sha=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))).toString('hex');const shown={source_node_id:'source',source_head:'original',source_sha256:'a'.repeat(64),provider:'jira',content,sha256:sha};let allowed=true,changed=false,prepares=0,calls=[];
 const api={previewCorporateWorkflow:async()=>({...shown,...(changed?{source_sha256:'b'.repeat(64)}:{})}),prepareCorporateWorkflow:async(p,n,h,provider,plan,hash,consent)=>{assert.equal(consent,true);assert.equal(hash,sha);prepares++;return {source_node_id:n,source_head:h,content,sha256:sha,issue_id:'workflow:'+sha,preview_id:'receipt',content_type:'application/vnd.mnemos.task-tracker+json'};},checkPrivateVersionRead:async()=>{if(!allowed)throw Error('revoked');},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,r)=>{calls.push(structuredClone(r));if(calls.length===1)throw Error('lost after commit');return {node_id:'created',head:'new-head'};},readDraftDocument:async()=>({exists:true})};
 const c=new CorporateWorkflows(storage,'https://objects.test',async(_url,options)=>{assert.equal(new TextDecoder().decode(options.body),content);return {ok:true};});
 await assert.rejects(c.prepare(api,'p',shown,{},false));assert.equal(prepares,0);changed=true;await assert.rejects(c.prepare(api,'p',shown,{},true));assert.equal(prepares,0);changed=false;
 const prepared=await c.prepare(api,'p',shown,{},true);assert.equal(prepared.state,'prepared');assert(!JSON.stringify([...entries]).includes('sentinel'));await assert.rejects(c.execute(api,prepared.id));
 const restarted=new CorporateWorkflows(storage,'https://objects.test',async()=>{throw Error('second upload');});const recovered=await restarted.prepare(api,'p',shown,{},true);assert.equal(recovered.id,prepared.id);assert.equal(recovered.state,'unconfirmed');assert.equal(prepares,1);
 const done=await restarted.execute(api,prepared.id);assert.equal(done.node_id,'created');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].corporate_preview_id,'receipt');await restarted.execute(api,prepared.id);assert.equal(calls.length,2);allowed=false;await assert.rejects(restarted.execute(api,prepared.id));assert.equal(calls.length,2);
});
