import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {JSDOM} from 'jsdom';
const built=await build({stdin:{contents:'export {CorporateImportView} from "./app/corporate-import.ts";',resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false});const {CorporateImportView}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
test('Jira preview uses the current source head, preserves raw numbers and clears denied data',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true;
 const api={listPrivateDocuments:async()=>({documents:[{node_id:'source',name:'Export',content_type:'application/json'}],next_cursor:''}),readDraftDocument:async()=>({head:'exact-head',exists:true,content_type:'application/json'}),previewJiraImport:async(project,node,head)=>{assert.deepEqual([project,node,head],['p','source','exact-head']);if(!allowed)throw Error('denied');return {source_head:head,source_sha256:'hash',preview:{source_id:'jira-a',issues:[{key:'A-1',title:'<img src=x>',record:'{"custom":9007199254740993}',missing_fields:['security'],referenced_issues:['2']}],unresolved:[{from:'1',to:'2'}],pending_attachments:1}};}};
 const view=new CorporateImportView(root,api,[{id:'p',name:'Project'}],()=>{});await view.load('p');await view.preview('source');assert(root.textContent.includes('9007199254740993'));assert(root.textContent.includes('Импорт не выполнен'));assert.equal(root.querySelector('img'),null);
 allowed=false;await view.preview('source');assert(!root.textContent.includes('9007199254740993'));assert(!root.textContent.includes('A-1'));assert(root.textContent.includes('Предпросмотр недоступен'));
});
test('Closing Jira preview during source lookup prevents the next request and late rendering',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let resolve,calls=0;
 const api={listPrivateDocuments:async()=>({documents:[],next_cursor:''}),readDraftDocument:()=>new Promise(r=>resolve=r),previewJiraImport:async()=>{calls++;}};
 const view=new CorporateImportView(root,api,[],()=>{root.textContent='closed';});await view.load('p');const pending=view.preview('source');[...root.querySelectorAll('button')].find(b=>b.textContent==='Закрыть перенос из Jira').click();resolve({head:'h',exists:true,content_type:'application/json'});await pending;assert.equal(calls,0);assert.equal(root.textContent,'closed');
});
test('Imported task origin uses its current version and clears source coordinates on denial',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true;
 const api={listPrivateDocuments:async()=>({documents:[],next_cursor:''}),readDraftDocument:async(p,n)=>({head:n==='copy'?'copy-current':'source-head',exists:true,content_type:'application/json'}),previewJiraImport:async()=>({source_node_id:'source',source_head:'source-head',source_sha256:'hash',preview:{source_id:'jira',issues:[{id:'1',key:'A-1',title:'Task',record:'{}',missing_fields:[],referenced_issues:[]}],unresolved:[],pending_attachments:0}}),prepareCorporateTask:async()=>({id:'intent',state:'created',name:'Review',node_id:'copy'}),readCorporateOrigin:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','copy','copy-current']);if(!allowed)throw Error('denied');return {provider:'jira',entity_kind:'task',entity_id:'1',source_node_id:'private-source-marker',source_head:'original-version',source_sha256:'source-hash',output_sha256:'output-hash'};}};
 const view=new CorporateImportView(root,api,[],()=>{});await view.load('p');await view.preview('source');await view.prepare('1');await view.readOrigin();assert(root.textContent.includes('private-source-marker'));assert(root.textContent.includes('Последующие правки задачи'));
 allowed=false;await view.readOrigin();assert(!root.textContent.includes('private-source-marker'));assert(!root.textContent.includes('source-hash'));assert(root.textContent.includes('Предпросмотр недоступен'));
});
test('Bitrix uses its own adapter, preserves typed identities and clears denied source',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true;
 const api={listPrivateDocuments:async()=>({documents:[],next_cursor:''}),readDraftDocument:async()=>({head:'exact',exists:true,content_type:'application/json'}),previewJiraImport:async()=>{throw Error('wrong adapter');},previewBitrixImport:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','source','exact']);if(!allowed)throw Error('denied');return {source_head:h,source_sha256:'hash',preview:{source_id:'portal',records:[{kind:'task',id:'1',title:'<img src=x>',record:'{"n":9007199254740993}',missing_fields:[]},{kind:'department',id:'1',title:'Dept',record:'{}',missing_fields:[]}],references:[{from_kind:'task',from_id:'1',field:'responsibleId',to_kind:'person',to_id:'2',resolved:false}],missing_collections:['people']}};}};
 const view=new CorporateImportView(root,api,[],()=>{},'bitrix');await view.load('p');await view.preview('source');assert(root.textContent.includes('task 1'));assert(root.textContent.includes('department 1'));assert(root.textContent.includes('9007199254740993'));assert(root.textContent.includes('отсутствует в выборке'));assert.equal(root.querySelector('img'),null);assert(![...root.querySelectorAll('button')].some(b=>b.textContent.includes('Подготовить задачу')));
 allowed=false;await view.preview('source');assert(!root.textContent.includes('9007199254740993'));assert(root.textContent.includes('Предпросмотр недоступен'));
});
test('card invitations use the selected node, exact head and previous mode; denied updates clear choices',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let mode='',fail=false;const calls=[];
 const api={readDraftDocument:async(p,n)=>({head:'current',terms:[{metadata:{name:'Chosen card'}}]}),listPrivateDraftParticipants:async(p,n,h,c)=>{assert.deepEqual([p,n,h,c],['p','selected','current','']);return {head:h,next_cursor:'',participants:[{principal_id:'human',display_name:'<img src=x>',mode,can_read:true,can_write:false}]};},setPrivateDraftParticipant:async(...args)=>{calls.push(args);if(fail)throw Error('stale or revoked');mode=args[5];},listPrivateDocuments:async()=>({documents:[],next_cursor:''})};
 const view=new CorporateImportView(root,api,[],()=>{},'bitrix');await view.load('p');await view.readAccess('selected');
 assert.equal(root.querySelector('img'),null);assert(root.textContent.includes('Chosen card'));assert(![...root.querySelectorAll('button')].some(b=>b.textContent==='Редактирование: human'));
 await view.changeAccess('human','read');assert.deepEqual(calls[0],['p','selected','current','human','','read']);
 await view.changeAccess('human','');assert.deepEqual(calls[1],['p','selected','current','human','read','']);
 fail=true;await view.changeAccess('human','read');assert(!root.textContent.includes('<img src=x>'));assert(root.textContent.includes('Предпросмотр недоступен'));await view.changeAccess('human','read');assert.equal(calls.length,3);
});
test('Jira links follow an authorized exact-version target and clear revoked relationships',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true,changed=false;let resolved=0;
 const api={readDraftDocument:async(p,n)=>({exists:true,head:changed?'new-head':'head',terms:[{metadata:{name:n==='task'?'Task':'Confidential.docx'}}]}),readJiraLinks:async(p,n,h)=>{if(!allowed)throw Error('revoked');return {links:[n==='task'?{field:'attachment',kind:'document',entity_id:'attachment:71',label:'Confidential.docx'}:{field:'issue',kind:'task',entity_id:'201',label:'DOC-201'}]};},resolveCorporateTarget:async(p,n,h,k,id)=>{resolved++;assert.deepEqual([p,n,h,k,id],['p','task','head','document','attachment:71']);if(!allowed)throw Error('denied');return {node_id:'file'};},listPrivateDocuments:async()=>({documents:[],next_cursor:''})};
 const view=new CorporateImportView(root,api,[],()=>{});await view.load('p');await view.readLinks('task');assert(root.textContent.includes('Confidential.docx'));await view.followLink(0);assert.equal(resolved,1);assert(root.textContent.includes('Узел: file'));assert(root.textContent.includes('DOC-201'));
 allowed=false;await view.readLinks('file');assert(!root.textContent.includes('DOC-201'));assert(!root.textContent.includes('Confidential.docx'));assert(!root.textContent.includes('Узел: file'));
 allowed=true;await view.readLinks('task');changed=true;await view.followLink(0);assert(!root.textContent.includes('Узел: file'));assert(root.textContent.includes('Предпросмотр недоступен'));
});
test('Bitrix links follow an authorized exact-version target and clear revoked relationships',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true,changed=false;let resolved=0;
 const api={readDraftDocument:async(p,n)=>({exists:true,head:changed?'new-head':'head',terms:[{metadata:{name:n==='task'?'Task':'Confidential.docx'}}]}),readJiraLinks:async(p,n,h)=>{if(!allowed)throw Error('revoked');return {links:[n==='task'?{field:'attachment',kind:'document',entity_id:'file:71',label:'Confidential.docx'}:{field:'issue',kind:'task',entity_id:'task:201',label:'DOC-201'}]};},resolveCorporateTarget:async(p,n,h,k,id)=>{resolved++;assert.deepEqual([p,n,h,k,id],['p','task','head','document','file:71']);if(!allowed)throw Error('denied');return {node_id:'file'};},listPrivateDocuments:async()=>({documents:[],next_cursor:''})};
 const view=new CorporateImportView(root,api,[],()=>{},"bitrix");await view.load('p');await view.readLinks('task');assert(root.textContent.includes('Confidential.docx'));await view.followLink(0);assert.equal(resolved,1);assert(root.textContent.includes('Узел: file'));assert(root.textContent.includes('DOC-201'));
 allowed=false;await view.readLinks('file');assert(!root.textContent.includes('DOC-201'));assert(!root.textContent.includes('Confidential.docx'));assert(!root.textContent.includes('Узел: file'));
 allowed=true;await view.readLinks('task');changed=true;await view.followLink(0);assert(!root.textContent.includes('Узел: file'));assert(root.textContent.includes('Предпросмотр недоступен'));
});
test('Jira mapping sends the displayed source identity to the Jira preparation path',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let called=false;
 const source={record_sha256:'digest',status:'10001',responsible_id:'external:person'};
 const api={listPrivateDocuments:async()=>({documents:[],next_cursor:''}),readDraftDocument:async()=>({exists:true,head:'head',content_type:'application/json'}),previewJiraImport:async()=>({source_node_id:'source',source_head:'head',source_sha256:'hash',preview:{source_id:'jira',issues:[{id:'301',key:'WORK-301',title:'Task',record:'{}',missing_fields:[],referenced_issues:[],task_mapping_source:source}],unresolved:[],pending_attachments:0}}),prepareMappedCorporateTask:async()=>{throw Error('wrong provider');},prepareMappedJiraCorporateTask:async(...args)=>{called=true;assert.deepEqual(args.slice(0,4),['p','source','head','301']);assert.equal(args[4].source_responsible_id,'external:person');return {id:'intent',state:'prepared',name:'Jira 301',assignment:{status:'in_progress',assignee:'human'}};}};
 const view=new CorporateImportView(root,api,[],()=>{});await view.load('p');await view.preview('source');assert(root.textContent.includes('Сопоставить задачу: WORK-301'));view.startMapping('301');assert(root.textContent.includes('external:person'));await view.prepareMapped({source_record_sha256:'digest',source_status:'10001',source_responsible_id:'external:person',status:'in_progress',assignee_id:'human'});assert(called);assert(root.textContent.includes('Подтвердить создание назначенной задачи'));
});
test('Shared workflow preview pins source/provider and clears content on denied refresh',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true;
 const api={listPrivateDocuments:async()=>({documents:[],next_cursor:''}),readDraftDocument:async()=>({exists:true,head:'head',content_type:'application/json'}),previewJiraImport:async()=>({source_node_id:'source',source_head:'head',source_sha256:'hash',preview:{source_id:'jira',issues:[],unresolved:[],pending_attachments:0}}),previewCorporateWorkflow:async(...args)=>{assert.deepEqual(args,['p','source','head','jira',{title:'Reviewed'}]);if(!allowed)throw Error('denied');return {source_node_id:'source',source_head:'head',source_sha256:'hash',provider:'jira',content:'private-workflow-content',sha256:'output-hash'};}};
 const view=new CorporateImportView(root,api,[],()=>{});await view.load('p');await view.preview('source');await view.previewWorkflow('{"title":"Reviewed"}');assert(root.textContent.includes('private-workflow-content'));assert(root.textContent.includes('ещё не сохранён'));allowed=false;await view.preview('source');await view.previewWorkflow('{"title":"Reviewed"}');assert(!root.textContent.includes('private-workflow-content'));assert(!root.textContent.includes('output-hash'));
});

test('Workflow return preserves the selected task and rechecks current access without choosing another copy',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let allowed=true,head='h1',resolved=0;const reads=[];
 const api={listPrivateDocuments:async()=>({documents:[]}),readDraftDocument:async(p,n)=>{reads.push([p,n,head]);if(n==='workflow'&&!allowed)throw Error('revoked');return {exists:true,head,terms:[{metadata:{name:n}}]};},readJiraLinks:async(p,n,h)=>{assert.equal(h,head);return {links:n==='workflow'?[{source_task_id:'501',field:'attachment',kind:'document',entity_id:'file:601',label:'File'},{source_task_id:'502',field:'attachment',kind:'document',entity_id:'file:602',label:'Other file'}]:[{field:'task',kind:'task',entity_id:'task:501',label:'Separate copy'}]};},resolveCorporateTarget:async()=>{resolved++;return {node_id:'file'};}};
 const view=new CorporateImportView(root,api,[],()=>{});await view.load('p');await view.readLinks('workflow');await view.followLink(0);assert(root.textContent.includes('Вернуться к связям задачи 501 общего трекера'));
 head='h2';await view.returnToTask();assert.deepEqual(reads.at(-1),['p','workflow','h2']);assert.equal(resolved,1);assert(root.textContent.includes('Связи исходной задачи 501'));assert(!root.textContent.includes('Other file'));assert(!root.textContent.includes('Separate copy'));
 await view.followLink(0);allowed=false;await view.returnToTask();assert(root.textContent.includes('Предпросмотр недоступен'));assert(!root.textContent.includes('Связи исходной задачи'));assert(!root.textContent.includes('Вернуться к связям'));
 allowed=true;await view.readLinks('workflow');await view.followLink(0);await view.load('other-project');const before=reads.length;await view.returnToTask();assert.equal(reads.length,before);
});

test('Standalone file requires an explicit tracker with matching source and a present source task',async()=>{
 const dom=new JSDOM('<main/>');globalThis.document=dom.window.document;const root=document.querySelector('main');let mode='ok';const calls=[];
 const origin={provider:'bitrix24',source_node_id:'capture',source_sha256:'same',entity_kind:'document',entity_id:'file:601'};
 const api={listPrivateDocuments:async()=>({documents:[{node_id:'workflow',name:'Process',content_type:'application/vnd.mnemos.task-tracker+json'},{node_id:'other',name:'Process',content_type:'application/vnd.mnemos.task-tracker+json'}]}),readDraftDocument:async(p,n)=>{calls.push(n);if(n==='workflow'&&mode==='denied')throw Error('denied');return {exists:true,head:'head',terms:[{metadata:{name:n}}]};},readJiraLinks:async(p,n)=>({links:n==='file'?[{field:'task',kind:'task',entity_id:'task:501',label:'Task'}]:mode==='missing'?[]:[{source_task_id:'501',field:'attachment',kind:'document',entity_id:'file:601',label:'File'}]}),readCorporateOrigin:async(p,n)=>n==='file'?{...origin}:{...origin,entity_kind:'task',entity_id:mode==='single'?'task:501':'workflow:hash',source_sha256:mode==='foreign'?'other':'same'}};
 const view=new CorporateImportView(root,api,[],()=>{},'bitrix');await view.load('p');await view.readLinks('file');const choice=root.querySelector('select[aria-label="Трекер для задачи task:501"]');assert.equal(choice.value,'');assert.equal([...root.querySelectorAll('button')].find(b=>b.textContent==='Открыть задачу task:501 в выбранном трекере').disabled,true);assert(choice.textContent.includes('workflow'));assert(choice.textContent.includes('other'));
 await view.openTaskInTracker(0,'workflow');assert(root.textContent.includes('Узел: workflow'));assert(root.textContent.includes('Связи исходной задачи 501'));
 for(const failure of ['foreign','missing','denied','single']){mode=failure;await view.readLinks('file');await view.openTaskInTracker(0,'workflow');assert(root.textContent.includes('Предпросмотр недоступен'),failure);assert(!root.textContent.includes('Связи исходной задачи'),failure);}
});
