import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
const built=await build({stdin:{contents:'export {CorporateTaskCreation} from "./src/corporate-task-creation.ts";',resolveDir:process.cwd()},bundle:true,format:'esm',platform:'node',write:false});const {CorporateTaskCreation}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
test('Jira creation survives lost response and coordinator restart without changing request or retaining content',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};const original='a'.repeat(64),changed='b'.repeat(64),sourceHash='c'.repeat(64);let calls=[],allowed=true,prepares=0;
 const content='{"confidential-original":"sentinel"}',hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))).toString('hex');
 const api={previewJiraImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:sourceHash,preview:{issues:[{id:'1'}]}}),prepareJiraTask:async()=>{prepares++;return {source_node_id:'source',source_head:original,issue_id:'1',preview_id:'receipt',content_type:'application/vnd.mnemos.task-tracker+json',content,sha256:hash};},checkPrivateVersionRead:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','source',original]);if(!allowed)throw Error('revoked');},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,r)=>{calls.push(structuredClone(r));if(calls.length===1)throw Error('response lost after commit');return {node_id:'created',head:changed};},readDraftDocument:async()=>({exists:true})};
 const c=new CorporateTaskCreation(storage,'https://objects.test',async function(){assert.equal(this,undefined);return {ok:true};});const prepared=await c.prepare(api,'p','source',original,'1');assert.equal(calls.length,0);assert.equal(prepared.state,'prepared');assert(!JSON.stringify([...entries]).includes('sentinel'));
 await assert.rejects(c.execute(api,prepared.id));const restarted=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('must not upload twice');});const recovered=await restarted.prepare(api,'p','source',changed,'1');assert.equal(recovered.id,prepared.id);assert.equal(recovered.state,'unconfirmed');assert.equal(prepares,1);
 const done=await restarted.execute(api,prepared.id);assert.equal(done.state,'created');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].expected_head,original);assert.equal(calls[1].corporate_preview_id,'receipt');await restarted.execute(api,prepared.id);assert.equal(calls.length,2);
 allowed=false;await assert.rejects(restarted.execute(api,prepared.id));assert.equal(calls.length,2);
});

test('Bitrix card creation survives lost response and coordinator restart without changing request or retaining content',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};const original='a'.repeat(64),changed='b'.repeat(64),sourceHash='c'.repeat(64);let calls=[],allowed=true,prepares=0;
 const content='{"confidential-original":"sentinel"}',hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))).toString('hex');
 const api={previewBitrixImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:sourceHash,preview:{records:[{id:'1',kind:'company'}]}}),prepareBitrixRecord:async()=>{prepares++;return {source_node_id:'source',source_head:original,issue_id:'company:1',preview_id:'receipt',content_type:'application/json',content,sha256:hash};},checkPrivateVersionRead:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','source',original]);if(!allowed)throw Error('revoked');},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,r)=>{calls.push(structuredClone(r));if(calls.length===1)throw Error('response lost after commit');return {node_id:'created',head:changed};},readDraftDocument:async()=>({exists:true})};
 const c=new CorporateTaskCreation(storage,'https://objects.test',async function(){assert.equal(this,undefined);return {ok:true};});const prepared=await c.prepare(api,'p','source',original,'1','company');assert.equal(calls.length,0);assert.equal(prepared.state,'prepared');assert(!JSON.stringify([...entries]).includes('sentinel'));
 await assert.rejects(c.execute(api,prepared.id));const restarted=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('must not upload twice');});const recovered=await restarted.prepare(api,'p','source',changed,'1','company');assert.equal(recovered.id,prepared.id);assert.equal(recovered.state,'unconfirmed');assert.equal(prepares,1);
 const done=await restarted.execute(api,prepared.id);assert.equal(done.state,'created');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].expected_head,original);assert.equal(calls[1].corporate_preview_id,'receipt');await restarted.execute(api,prepared.id);assert.equal(calls.length,2);
 allowed=false;await assert.rejects(restarted.execute(api,prepared.id));assert.equal(calls.length,2);
});

test('Mapped Bitrix task creation survives lost response and coordinator restart without changing request or retaining content',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};const original='a'.repeat(64),changed='b'.repeat(64),sourceHash='c'.repeat(64);let calls=[],allowed=true,prepares=0;
 const content='{"confidential-original":"sentinel"}',hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))).toString('hex');
 const api={previewBitrixImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:sourceHash,preview:{records:[{id:'1',kind:'task'}]}}),prepareMappedBitrixTask:async()=>{prepares++;return {source_node_id:'source',source_head:original,issue_id:'task:1',preview_id:'receipt',content_type:'application/vnd.mnemos.task-tracker+json',content,sha256:hash};},checkPrivateVersionRead:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','source',original]);if(!allowed)throw Error('revoked');},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,r)=>{calls.push(structuredClone(r));if(calls.length===1)throw Error('response lost after commit');return {node_id:'created',head:changed};},readDraftDocument:async()=>({exists:true})};
 const c=new CorporateTaskCreation(storage,'https://objects.test',async function(){assert.equal(this,undefined);return {ok:true};});const prepared=await c.prepare(api,'p','source',original,'1','task',{status:'in_progress',assignee_id:'peer'});assert.equal(calls.length,0);assert.equal(prepared.state,'prepared');assert(!JSON.stringify([...entries]).includes('sentinel'));
 await assert.rejects(c.execute(api,prepared.id));const restarted=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('must not upload twice');});const recovered=await restarted.prepare(api,'p','source',changed,'1','task',{status:'in_progress',assignee_id:'peer'});assert.equal(recovered.id,prepared.id);assert.equal(recovered.state,'unconfirmed');assert.equal(prepares,1);
 const done=await restarted.execute(api,prepared.id);assert.equal(done.state,'created');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].expected_head,original);assert.equal(calls[1].corporate_preview_id,'receipt');await restarted.execute(api,prepared.id);assert.equal(calls.length,2);
 allowed=false;await assert.rejects(restarted.execute(api,prepared.id));assert.equal(calls.length,2);
});

test('Bitrix file uploads exact binary bytes and recovers the same private document request',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};
 const bytes=new Uint8Array([0,255,254,13,10]),hash=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex');const encoded=Buffer.from(bytes).toString('base64');let uploads=0;const calls=[];
 const api={previewBitrixImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:'a'.repeat(64),preview:{records:[{kind:'file',id:'101'}],files:[{object_id:'101',name:'Original.pdf',content_type:'application/pdf',available:true,size_bytes:5,sha256:hash}]}}),prepareBitrixFile:async()=>({preview_id:'receipt',source_node_id:'source',source_head:'head',entity_id:'file:101',name:'Original.pdf',content_type:'application/pdf',content_base64:encoded,sha256:hash,size_bytes:5}),checkPrivateVersionRead:async()=>{},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,request)=>{calls.push(structuredClone(request));if(calls.length===1)throw Error('lost response');return {node_id:'file',head:'created'};},readDraftDocument:async()=>({exists:true})};
 const creator=new CorporateTaskCreation(storage,'https://objects.test',async(url,options)=>{uploads++;assert.deepEqual(options.body,bytes);return {ok:true};});
 const prepared=await creator.prepare(api,'p','source','head','101','file');assert.equal(prepared.document.content_type,'application/pdf');assert.equal(prepared.name,'Original.pdf');assert(!JSON.stringify([...entries]).includes(encoded));
 await assert.rejects(creator.execute(api,prepared.id));const recovered=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('duplicate upload');});await recovered.prepare(api,'p','source','head','101','file');const done=await recovered.execute(api,prepared.id);assert.equal(done.node_id,'file');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[0].content_type,'application/pdf');assert.equal(uploads,1);
});

test('Jira attachment uploads exact binary bytes and recovers the same private document request',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};
 const bytes=new Uint8Array([0,255,254,13,10]),hash=Buffer.from(await crypto.subtle.digest('SHA-256',bytes)).toString('hex');const encoded=Buffer.from(bytes).toString('base64');let uploads=0;const calls=[];
 const api={previewJiraImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:'a'.repeat(64),preview:{issues:[{id:'101'}],attachments:[{id:'44',issue_id:'101',issue_key:'TEAM-1',name:'Original.pdf',content_type:'application/pdf',available:true,size_bytes:5,sha256:hash}]}}),prepareJiraFile:async()=>({preview_id:'receipt',source_node_id:'source',source_head:'head',entity_id:'attachment:44',name:'Original.pdf',content_type:'application/pdf',content_base64:encoded,sha256:hash,size_bytes:5}),checkPrivateVersionRead:async()=>{},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,request)=>{calls.push(structuredClone(request));if(calls.length===1)throw Error('lost response');return {node_id:'file',head:'created'};},readDraftDocument:async()=>({exists:true})};
 const creator=new CorporateTaskCreation(storage,'https://objects.test',async(url,options)=>{uploads++;assert.deepEqual(options.body,bytes);return {ok:true};});
 const prepared=await creator.prepare(api,'p','source','head','44','attachment',undefined,'101');assert.equal(prepared.document.content_type,'application/pdf');assert.equal(prepared.name,'Original.pdf');assert(!JSON.stringify([...entries]).includes(encoded));
 await assert.rejects(creator.execute(api,prepared.id));const recovered=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('duplicate upload');});await recovered.prepare(api,'p','source','head','44','attachment',undefined,'101');const done=await recovered.execute(api,prepared.id);assert.equal(done.node_id,'file');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[0].content_type,'application/pdf');assert.equal(uploads,1);
});

test('Mapped Jira task creation survives lost response and coordinator restart without changing request or retaining content',async()=>{
 const entries=new Map(),storage={get:k=>structuredClone(entries.get(k)),put:(k,v)=>entries.set(k,structuredClone(v)),delete:k=>entries.delete(k)};const original='a'.repeat(64),changed='b'.repeat(64),sourceHash='c'.repeat(64);let calls=[],allowed=true,prepares=0;
 const content='{"confidential-original":"sentinel"}',hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content))).toString('hex');
 const api={previewJiraImport:async(p,n,h)=>({source_node_id:n,source_head:h,source_sha256:sourceHash,preview:{issues:[{id:'1'}]}}),prepareMappedJiraTask:async()=>{prepares++;return {source_node_id:'source',source_head:original,issue_id:'1',preview_id:'receipt',content_type:'application/vnd.mnemos.task-tracker+json',content,sha256:hash};},checkPrivateVersionRead:async(p,n,h)=>{assert.deepEqual([p,n,h],['p','source',original]);if(!allowed)throw Error('revoked');},beginNativeUpload:async(p,size,sum)=>({url:'https://objects.test/upload',method:'PUT',content_length:size,checksum_header:'x-amz-checksum-sha256',checksum_value:sum,upload_id:'upload'}),createPrivateDocument:async(p,r)=>{calls.push(structuredClone(r));if(calls.length===1)throw Error('response lost after commit');return {node_id:'created',head:changed};},readDraftDocument:async()=>({exists:true})};
 const c=new CorporateTaskCreation(storage,'https://objects.test',async function(){assert.equal(this,undefined);return {ok:true};});const prepared=await c.prepare(api,'p','source',original,'1','jira-task',{status:'in_progress',assignee_id:'peer'});assert.equal(calls.length,0);assert.equal(prepared.state,'prepared');assert(!JSON.stringify([...entries]).includes('sentinel'));
 await assert.rejects(c.execute(api,prepared.id));const restarted=new CorporateTaskCreation(storage,'https://objects.test',async()=>{throw Error('must not upload twice');});const recovered=await restarted.prepare(api,'p','source',changed,'1','jira-task',{status:'in_progress',assignee_id:'peer'});assert.equal(recovered.id,prepared.id);assert.equal(recovered.state,'unconfirmed');assert.equal(prepares,1);
 const done=await restarted.execute(api,prepared.id);assert.equal(done.state,'created');assert.deepEqual(calls[0],calls[1]);assert.equal(calls[1].expected_head,original);assert.equal(calls[1].corporate_preview_id,'receipt');await restarted.execute(api,prepared.id);assert.equal(calls.length,2);
 allowed=false;await assert.rejects(restarted.execute(api,prepared.id));assert.equal(calls.length,2);
});
