import test from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {createHash} from 'node:crypto';
const compiled=await build({entryPoints:['app/mail-attachment.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {readMailAttachment}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
const bytes=Uint8Array.from({length:20736},(_,i)=>i%256),sha256=createHash('sha256').update(bytes).digest('hex');
const query={limit:5,cursor:'saved-page',search:{text:'смета'}},expected={provider:'imap',query_sha256:'a'.repeat(64)},file={attachment_id:'mime:0',filename:'same.bin',kind:'file',sha256:null};
function reader(change=()=>{}){const calls=[];return {calls,read:async q=>{calls.push(q);assert.deepEqual({...q,attachment:undefined},{...query,attachment:undefined});const a=q.attachment;const end=Math.min(bytes.length,a.offset+a.max_bytes);const result={...expected,messages:[],truncated:false,attachment:{message_id:'message',attachment_id:file.attachment_id,total_size:bytes.length,sha256,offset:a.offset,content_base64:Buffer.from(bytes.subarray(a.offset,end)).toString('base64'),complete:end===bytes.length,...(end<bytes.length?{next_offset:end}:{})}};change(result,calls.length);return result}}}
test('assembles binary bytes with unchanged selection and pins full-file digest',async()=>{const r=reader();assert.deepEqual(await readMailAttachment(r.read,query,'message',file,expected,()=>true),bytes);assert.equal(r.calls.length,3);assert.equal(r.calls[0].attachment.expected_sha256,undefined);assert(r.calls.slice(1).every(q=>q.attachment.expected_sha256===sha256));});
test('changed identity, digest, bytes, size, progress or completion never returns a file',async()=>{
 for(const change of [r=>r.provider='google',r=>r.attachment.message_id='other',r=>r.attachment.attachment_id='mime:1',r=>r.attachment.sha256='b'.repeat(64),r=>r.attachment.total_size++,r=>r.attachment.next_offset=0,r=>r.attachment.content_base64=Buffer.alloc(8192).toString('base64'),r=>r.attachment.complete=true]){const r=reader((value,n)=>{if(n===2)change(value)});await assert.rejects(readMailAttachment(r.read,query,'message',file,expected,()=>true));}
});
test('revoked read or closed screen stops assembling; references do not read',async()=>{let active=true;const r=reader(()=>{active=false});await assert.rejects(readMailAttachment(r.read,query,'message',file,expected,()=>active));assert.equal(r.calls.length,1);let calls=0;await assert.rejects(readMailAttachment(async()=>{calls++;throw Error('denied')},query,'message',file,expected,()=>true));assert.equal(calls,1);await assert.rejects(readMailAttachment(async()=>{calls++;},query,'message',{...file,kind:'reference'},expected,()=>true));assert.equal(calls,1);});
