// @vitest-environment jsdom
import {act} from 'react';import {createRoot} from 'react-dom/client';import {beforeEach,afterEach,expect,test,vi} from 'vitest';
const mocks=vi.hoisted(()=>({api:{},open:vi.fn(),read:vi.fn(),allow:vi.fn(),dispose:vi.fn()}));
vi.mock('./AuthContext',()=>({useAuthenticatedApi:()=>({authenticatedApi:mocks.api})}));vi.mock('./accountCapabilities',()=>({openBlueprintTemplatesFrame:(...args:unknown[])=>mocks.open(...args)}));vi.mock('./disposeGatekeeperFrame',()=>({disposeGatekeeperFrame:(...args:unknown[])=>mocks.dispose(...args)}));
import SelectedTemplateAgentAccess from './SelectedTemplateAgentAccess';
const items=[{accountId:0,reference:{scope_id:'team',template_key:'form',revision:1},title:'Форма',purpose:'ТЗ',kind:'document' as const}];const plan={bindingId:'agent',ready:false,scopes:[{scopeId:'team',title:'Группа',revision:0,enabled:false}]};let host:HTMLDivElement,root:ReturnType<typeof createRoot>;
beforeEach(()=>{vi.resetAllMocks();(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;mocks.open.mockResolvedValue({blueprintTemplates:{selector:{agentAccess:mocks.read,allowAgentAccess:mocks.allow}}});mocks.read.mockResolvedValue(plan);host=document.createElement('div');document.body.append(host);root=createRoot(host)});afterEach(async()=>{await act(async()=>root.unmount());host.remove()});
test('Не выдаёт разрешение при выборе; явная кнопка показывает область и проверяет весь набор снова',async()=>{const ready=vi.fn();await act(async()=>root.render(<SelectedTemplateAgentAccess items={items} onReady={ready}/>));expect(ready).not.toHaveBeenCalledWith(JSON.stringify([[0,items[0].reference]]));expect(mocks.allow).not.toHaveBeenCalled();expect(host.textContent).toContain('опубликованные шаблоны этой области');mocks.allow.mockResolvedValue({...plan,ready:true});mocks.read.mockResolvedValue({...plan,ready:true,scopes:[{...plan.scopes[0],enabled:true,revision:1}]});await act(async()=>Array.from(host.querySelectorAll('button')).find(b=>b.textContent?.startsWith('Разрешить чтение'))!.click());expect(mocks.allow).toHaveBeenCalledWith([items[0].reference],'team','agent',0);expect(ready).toHaveBeenCalledWith(JSON.stringify([[0,items[0].reference]]));expect(host.textContent).toContain('Агент может прочитать выбранные версии');});
test('Потеря ответа не подтверждает доступ; повтор читает сохранённое состояние без повторной выдачи',async()=>{const ready=vi.fn();await act(async()=>root.render(<SelectedTemplateAgentAccess items={items} onReady={ready}/>));mocks.allow.mockRejectedValue(Error('lost'));await act(async()=>host.querySelector('button')!.click());expect(ready).not.toHaveBeenCalledWith(JSON.stringify([[0,items[0].reference]]));expect(host.textContent).toContain('не подтверждено');mocks.read.mockResolvedValue({...plan,ready:true,scopes:[{...plan.scopes[0],enabled:true,revision:1}]});await act(async()=>Array.from(host.querySelectorAll('button')).find(b=>b.textContent?.startsWith('Проверить'))!.click());expect(ready.mock.calls.filter(call=>call[0]!=='')).toHaveLength(1);expect(mocks.allow).toHaveBeenCalledTimes(1);});
test('Смена набора и выход освобождают кадр и не подтверждают поздний доступ',async()=>{const ready=vi.fn();let finish!:(value:unknown)=>void;mocks.read.mockReturnValue(new Promise(resolve=>{finish=resolve}));await act(async()=>root.render(<SelectedTemplateAgentAccess items={items} onReady={ready}/>));await act(async()=>root.unmount());await act(async()=>finish({...plan,ready:true}));expect(ready).not.toHaveBeenCalledWith(JSON.stringify([[0,items[0].reference]]));expect(mocks.dispose).toHaveBeenCalled();});

test('Новый цикл проверки сбрасывает прежнее подтверждение даже для того же набора',async()=>{const ready=vi.fn();mocks.read.mockResolvedValue({...plan,ready:true});await act(async()=>root.render(<SelectedTemplateAgentAccess items={items} onReady={ready}/>));expect(ready).toHaveBeenLastCalledWith(JSON.stringify([[0,items[0].reference]]));await act(async()=>root.render(<span>Просмотр</span>));expect(ready).toHaveBeenLastCalledWith('');mocks.read.mockReturnValue(new Promise(()=>{}));await act(async()=>root.render(<SelectedTemplateAgentAccess items={items} onReady={ready}/>));expect(ready).toHaveBeenLastCalledWith('');});
