import {CalendarEventsView} from './calendar-events.ts';
import type {CalDAVManagement} from '../src/caldav-types.ts';
import type {CalendarDraftManagement,CalendarDraftReview,CalendarDraftPage} from '../src/calendar-drafts.ts';
import type {MnemosAccountSession} from '../src/account-session.ts';
import type {CalendarConnectionInfo,CalendarGrantState} from '../src/calendar-connections.ts';
type API=Pick<MnemosAccountSession,'listCalendarConnections'|'readCalendarEvents'|'readCalendarConnection'|'readCalendarGrantState'|'setCalendarReadGrant'|'disableCalendarConnection'|'listAgentConnections'> & CalendarDraftManagement & Pick<CalDAVManagement,'checkCalDAVScheduling'>;
/** Minimal owner management for an existing calendar connection. */
export class CalendarConnectionsView {
 private events?:CalendarEventsView;
 private connections?:Awaited<ReturnType<API['listCalendarConnections']>>;
 private invitationsAvailable?:boolean;
 private draft?:CalendarDraftReview;private draftPage?:CalendarDraftPage;
 private id='';private principal='';private receipt?:CalendarConnectionInfo;private grant?:CalendarGrantState;
 private agents:Awaited<ReturnType<API['listAgentConnections']>>['connections']=[];private cursor='';
 private busy=false;private closed=false;private notice='';
 constructor(private root:HTMLElement,private api:API,private close:()=>void,private creator?:(id:string,sha256:string)=>Promise<NonNullable<CalendarDraftReview['execution']>>){}
 private async run(work:()=>Promise<void>){if(this.closed||this.busy)return;this.busy=true;this.notice='';this.render();try{await work();}catch{this.connections=undefined;this.invitationsAvailable=undefined;this.receipt=undefined;this.draft=undefined;this.draftPage=undefined;this.grant=undefined;this.notice='Результат не подтверждён. Обновите состояние перед повтором.';}finally{this.busy=false;if(!this.closed)this.render();}}
 async listConnections(more=false){await this.run(async()=>{const page=await this.api.listCalendarConnections(more?this.connections?.next_cursor:'');if(!this.closed)this.connections={...page,connections:more?[...(this.connections?.connections??[]),...page.connections]:page.connections};});}
 async load(id:string){await this.run(async()=>{this.id=id;this.invitationsAvailable=undefined;this.receipt=undefined;this.draft=undefined;this.draftPage=undefined;this.grant=undefined;const receipt=await this.api.readCalendarConnection(id);if(!this.closed)this.receipt=receipt;});}
 async listAgents(more=false){await this.run(async()=>{const result=await this.api.listAgentConnections(more?this.cursor:'');if(this.closed)return;this.agents=more?[...this.agents,...result.connections]:result.connections;this.cursor=result.next_cursor??'';});}
 async select(principal:string){await this.run(async()=>{this.principal=principal;this.grant=undefined;const state=await this.api.readCalendarGrantState(this.id,principal);if(!this.closed)this.grant=state;});}
 async decide(enabled:boolean){const state=this.grant;if(!state)return;await this.run(async()=>{this.grant=undefined;await this.api.setCalendarReadGrant(state.connection_id,{principal_id:state.principal_id,connection_revision:state.connection_revision,expected_revision:state.revision,enabled});const current=await this.api.readCalendarGrantState(state.connection_id,state.principal_id);if(!this.closed){this.grant=current;this.notice=enabled?'Разрешение чтения сохранено.':'Разрешение чтения отозвано.';}});}
 async disable(){const receipt=this.receipt;if(!receipt)return;await this.run(async()=>{this.draft=undefined;this.draftPage=undefined;this.grant=undefined;await this.api.disableCalendarConnection(receipt.connection_id,receipt.revision);const current=await this.api.readCalendarConnection(receipt.connection_id);if(!this.closed){this.receipt=current;this.notice='Подключение отключено.';}});}
 async listDrafts(more=false){await this.run(async()=>{const page=await this.api.listCalendarDrafts(this.id,more?this.draftPage?.next_cursor:'');if(!this.closed)this.draftPage={...page,drafts:more?[...(this.draftPage?.drafts??[]),...page.drafts]:page.drafts};});}
 async openDraft(id:string){await this.run(async()=>{this.draft=undefined;this.invitationsAvailable=undefined;const draft=await this.api.readCalendarDraft(id);if(draft.connection_id!==this.id)throw Error('Connection changed');if(this.needsScheduling(draft)&&!draft.execution){const calendar=this.receipt!.calendar_id;const result=await this.api.checkCalDAVScheduling(calendar);if(result.calendar_id!==calendar)throw Error('Calendar changed');if(!this.closed)this.invitationsAvailable=result.available;}if(!this.closed)this.draft=draft;});}
 private needsScheduling(draft:CalendarDraftReview){return draft.content.attendees.length>0&&['apple','yandex','caldav'].includes(this.receipt?.provider??'');}
 async decideDraft(approved:boolean){const draft=this.draft;if(!draft||draft.state!=='pending')return;await this.run(async()=>{this.draft=undefined;this.draftPage=undefined;const result=await this.api.decideCalendarDraft(draft.id,draft.sha256,approved);if(result.connection_id!==this.id||result.sha256!==draft.sha256)throw Error('Draft changed');if(!this.closed){this.draft=result;this.notice='Решение сохранено. Событие в календаре ещё не создано.';}});}
 async createDraft(){const draft=this.draft;if(!draft||draft.state!=='approved'||draft.execution||(this.needsScheduling(draft)&&this.invitationsAvailable!==true)||!this.creator||!['google','microsoft','apple','yandex','caldav'].includes(this.receipt?.provider??'')||!this.receipt?.enabled)return;await this.run(async()=>{this.draft=undefined;this.draftPage=undefined;await this.creator!(draft.id,draft.sha256);const current=await this.api.readCalendarDraft(draft.id);if(current.connection_id!==this.id||current.sha256!==draft.sha256)throw Error('Draft changed');if(!this.closed){this.draft=current;this.notice=current.execution?.state==='created'?'Событие создано в календаре.':'Результат создания не подтверждён. Проверьте календарь.';}});}
 render(){if(this.closed)return;this.events?.dispose();this.events=undefined;this.root.replaceChildren();const text=(value:string,tag='p')=>{const e=document.createElement(tag);e.textContent=value;this.root.append(e);};const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.textContent=label;b.disabled=this.busy;b.onclick=action;this.root.append(b);return b;};
 text('Доступ к календарю','h2');button('Закрыть календарь',()=>{this.closed=true;this.events?.dispose();this.events=undefined;this.invitationsAvailable=undefined;this.receipt=undefined;this.draft=undefined;this.draftPage=undefined;this.grant=undefined;this.root.replaceChildren();this.close();}).disabled=false;
 const label=document.createElement('label');label.textContent='ID подключения календаря';const input=document.createElement('input');input.setAttribute('aria-label',label.textContent);input.value=this.id;input.disabled=this.busy;label.append(input);this.root.append(label);button('Обновить календарь',()=>void this.load(input.value.trim()));
 button('Мои календари',()=>void this.listConnections());
 if(this.connections){for(const c of this.connections.connections)button(`${c.provider} · ${c.project_id} · ${c.calendar_id}${c.enabled?'':' (отключён)'}`,()=>void this.load(c.connection_id));if(this.connections.next_cursor)button('Ещё календари',()=>void this.listConnections(true));else if(!this.connections.connections.length)text('Подключённых календарей нет.');}
 if(this.notice)text(this.notice);if(!this.receipt)return;
 text(`${this.receipt.provider}: ${this.receipt.calendar_id}`);if(this.receipt.provider==='microsoft')text('Для создания встреч нужно разрешение Outlook на запись календаря. Для старого подключения: повторите вход в Outlook через Подключения, затем заново выберите календарь.');text(`Проект: ${this.receipt.project_id}. Подключение ${this.receipt.enabled?'включено':'отключено'}.`);
 if(this.receipt.enabled)button('События календаря',()=>{this.events?.dispose();const section=document.createElement('section');this.root.append(section);this.events=new CalendarEventsView(section,this.api,this.receipt!);this.events.render();});
 if(this.receipt.enabled)button('Отключить календарь',()=>void this.disable());
 if(this.receipt.enabled)button('Показать предложения встреч',()=>void this.listDrafts());
 if(this.draftPage){for(const draft of this.draftPage.drafts)button(draft.title,()=>void this.openDraft(draft.id));if(this.draftPage.next_cursor)button('Ещё предложения встреч',()=>void this.listDrafts(true));else if(!this.draftPage.drafts.length)text('Предложений встреч нет.');}
 if(this.draft){const d=this.draft; text(d.content.title,'h3');text('Начало (UTC): '+d.content.start);text('Конец (UTC): '+d.content.end);text('Участники: '+(d.content.attendees.join(', ')||'без приглашённых'));text('Место: '+d.content.location);const description=document.createElement('pre');description.textContent=d.content.description;description.style.whiteSpace='pre-wrap';this.root.append(description);text('Агент: '+d.agent_id);text('Состояние: '+({pending:'ожидает решения',approved:'согласовано',rejected:'отклонено'}[d.state]));text('Согласование само по себе не создаёт событие и не отправляет приглашения.');if(d.execution?.state==='created'){text('Событие создано. ID: '+d.execution.event_id);if(d.content.attendees.length)text('Доставка приглашений участникам отдельно не подтверждена.');}else if(d.execution?.state==='attempted')text('Результат создания неизвестен. Проверьте календарь перед новым предложением; повтор отключён.');else if(d.state==='approved'&&this.receipt.enabled&&['google','microsoft','apple','yandex','caldav'].includes(this.receipt.provider)&&this.creator){if(this.needsScheduling(d)&&this.invitationsAvailable!==true){text('Этот календарь не подтверждает поддержку приглашений. Встреча не создана. Выберите календарь с поддержкой приглашений или предложите встречу без участников.');}else{text(d.content.attendees.length?'Создание добавит событие в этот календарь и передаст приглашения календарному сервису. Доставку каждому участнику это не подтверждает.':'Создание добавит личное событие без приглашений.');button(d.content.attendees.length?'Создать встречу и отправить приглашения':'Создать встречу',()=>void this.createDraft());}}if(d.state==='pending'&&this.receipt.enabled){button('Согласовать встречу',()=>void this.decideDraft(true));button('Отклонить встречу',()=>void this.decideDraft(false));}}
 button('Показать моих агентов',()=>void this.listAgents());
 for(const agent of this.agents)button(`${agent.agent_principal_id}${agent.revoked?' (отозван)':''}`,()=>void this.select(agent.agent_principal_id));
 if(this.cursor)button('Ещё агенты',()=>void this.listAgents(true));
 if(this.grant){text(`Агент: ${this.principal}. Разрешение чтения ${this.grant.enabled?'сохранено':this.grant.revision===0?'не выдавалось':'отозвано'}.`);text('Фактическое чтение также требует действующих прав проекта и подключения.');if(this.grant.enabled)button('Отозвать чтение календаря',()=>void this.decide(false));else if(this.grant.connection_enabled&&!this.agents.some(agent=>agent.agent_principal_id===this.principal&&agent.revoked))button('Разрешить чтение календаря',()=>void this.decide(true));}
 }
}
