import {BitrixDepartmentView} from "./bitrix-department.ts";
import type {CorporateWorkflowState} from "../src/corporate-workflow.ts";
import type {CorporateUpdateState} from "../src/corporate-update.ts";
import type {CorporateCardEdit} from "../src/corporate-card.ts";
import type {CorporateTaskManagement,CorporateTaskState} from "../src/corporate-task-creation.ts";
import type {MnemosAccountSession} from "../src/account-session.ts";
import type {PrivateDocumentPage,PrivateParticipantPage,PrivateParticipantMode} from "../src/mnemos-api.ts";
import type {JiraImportPreview,BitrixImportPreview,BitrixTaskMapping,CorporateOrigin} from "../src/corporate-import.ts";
type API=Pick<MnemosAccountSession,"listOrganizationRoles"|"previewBitrixDepartmentMembership"|"applyBitrixDepartmentMembership"|"previewCorporateWorkflow"|"readJiraLinks"|"resolveCorporateTarget"|"resolveBitrixRecordUpdate"|"previewBitrixRecordUpdate"|"listPrivateDraftParticipants"|"setPrivateDraftParticipant"|"listPrivateDocuments"|"readDraftDocument"|"previewJiraImport"|"previewBitrixImport"|"readCorporateOrigin"> & CorporateTaskManagement;
export class CorporateImportView {
 private linkReturn?:{project:string;node:string;task:string};
 private workflowPlan?:unknown;
 private workflowPending?:CorporateWorkflowState;
 private workflow?:Awaited<ReturnType<MnemosAccountSession["previewCorporateWorkflow"]>>;
 private links?:{node:string;head:string;name:string;task?:string;value:Awaited<ReturnType<MnemosAccountSession["readJiraLinks"]>>};
 private mapping?:{node:string;head:string;id:string;title:string;source:{record_sha256:string;status:string;responsible_id:string}};
 private access?:{node:string;name:string;page:PrivateParticipantPage};
 private pendingUpdate?:CorporateUpdateState;
 private update?:Awaited<ReturnType<MnemosAccountSession["previewBitrixRecordUpdate"]>>;
 private cardNode="";
 private card?:CorporateCardEdit;
 private pending?:CorporateTaskState;
 private origin?:CorporateOrigin|null;
 private project="";private page?:PrivateDocumentPage;private result?:JiraImportPreview|BitrixImportPreview;private busy=false;private closed=false;private notice="";
 constructor(private root:HTMLElement,private api:API,private projects:ReadonlyArray<{id:string;name:string}>,private close:()=>void,private provider:"jira"|"bitrix"="jira"){}
 private async run(work:()=>Promise<void>){if(this.closed||this.busy)return;this.busy=true;this.workflow=undefined;this.links=undefined;this.update=undefined;this.result=undefined;this.origin=undefined;this.card=undefined;this.access=undefined;this.mapping=undefined;this.notice="";this.render();try{await work();}catch{this.page=undefined;this.result=undefined;this.notice="Предпросмотр недоступен. Проверьте права, версию и формат. Если сохраняли карточку, перечитайте её перед новой правкой.";}finally{this.busy=false;if(!this.closed)this.render();}}
 async load(project:string,cursor=""){await this.run(async()=>{this.linkReturn=undefined;this.project=project;this.page=undefined;this.pending=undefined;this.pendingUpdate=undefined;this.workflowPending=undefined;this.workflowPlan=undefined;const page=await this.api.listPrivateDocuments(project,cursor);if(!this.closed)this.page=page;});}
 async preview(node:string){await this.run(async()=>{const doc=await this.api.readDraftDocument(this.project,node);if(this.closed)return;if(!doc.exists||doc.conflicted||doc.content_type!=="application/json")throw Error("Unavailable source");const result=await (this.provider==="jira"?this.api.previewJiraImport(this.project,node,doc.head):this.api.previewBitrixImport(this.project,node,doc.head));if(!this.closed)this.result=result;});}
 openDepartment(person:string,department:string){const source=this.result;if(!source||this.busy||this.closed)return;const view=new BitrixDepartmentView(this.root,this.api,{project:this.project,node:source.source_node_id,head:source.source_head,sha256:source.source_sha256,person,department},()=>this.render());view.render();}
 async prepare(issue:string){const source=this.result;if(!source)return;this.pending=undefined;await this.run(async()=>{const pending=await this.api.prepareCorporateTask(this.project,source.source_node_id,source.source_head,issue);if(!this.closed)this.pending=pending;});}
 startMapping(id:string){const source=this.result;if(!source)return;const row="records" in source.preview?source.preview.records.find(r=>r.id===id&&r.kind==="task"):source.preview.issues.find(r=>r.id===id);if(!row?.task_mapping_source)return;this.mapping={node:source.source_node_id,head:source.source_head,id,title:row.title,source:row.task_mapping_source};this.result=undefined;this.pending=undefined;this.render();}

 async prepareMapped(decision:BitrixTaskMapping){const m=this.mapping;if(!m)return;await this.run(async()=>{const pending=await (this.provider==="jira"?this.api.prepareMappedJiraCorporateTask(this.project,m.node,m.head,m.id,decision):this.api.prepareMappedCorporateTask(this.project,m.node,m.head,m.id,decision));if(!this.closed)this.pending=pending;});}
 async prepareAttachment(issue:string,attachment:string){const source=this.result;if(!source)return;this.pending=undefined;await this.run(async()=>{const pending=await this.api.prepareCorporateAttachment(this.project,source.source_node_id,source.source_head,issue,attachment);if(!this.closed)this.pending=pending;});}
 async prepareRecord(kind:string,id:string){const source=this.result;if(!source)return;this.pending=undefined;await this.run(async()=>{const pending=await this.api.prepareCorporateRecord(this.project,source.source_node_id,source.source_head,kind,id);if(!this.closed)this.pending=pending;});}
 async confirm(){const saved=this.pending;if(!saved)return;this.pending={...saved,state:"unconfirmed"};await this.run(async()=>{const result=await this.api.executeCorporateTask(saved.id);if(!this.closed)this.pending=result;});}
 async readCard(){const node=this.pending?.node_id;if(!node)return;await this.run(async()=>{const card=await this.api.readCorporateCard(this.project,node);if(this.closed)return;const pending=await this.api.recoverCorporateUpdate(this.project,node);if(!this.closed){this.cardNode=node;this.card=card;this.pendingUpdate=pending??undefined;}});}
 async prepareUpdate(){const shown=this.update;if(!shown)return;await this.run(async()=>{const state=await this.api.prepareCorporateUpdate(this.project,shown);if(!this.closed)this.pendingUpdate=state;});}
 async applyUpdate(){const saved=this.pendingUpdate;if(!saved)return;this.pendingUpdate={...saved,state:"unconfirmed"};await this.run(async()=>{const state=await this.api.executeCorporateUpdate(saved.id);if(!this.closed){this.pendingUpdate=state;this.cardNode=state.node_id;this.card=await this.api.readCorporateCard(this.project,state.node_id);}});}
 async resolveUpdate(choice:"local"|"incoming"){const update=this.update;if(!update||!update.plan.conflicts.some(c=>c.field==="title"))return;await this.run(async()=>{const result=await this.api.resolveBitrixRecordUpdate(this.project,update.target_node_id,update.target_head,update.incoming_node_id,update.incoming_head,{current_sha256:update.current_sha256,incoming_sha256:update.incoming_sha256,title_choice:choice});if(!this.closed)this.update=result;});}
 async previewUpdate(incomingNode:string){const card=this.card,node=this.cardNode;if(!card||!node||!incomingNode)return;await this.run(async()=>{const incoming=await this.api.readDraftDocument(this.project,incomingNode);if(this.closed)return;const update=await this.api.previewBitrixRecordUpdate(this.project,node,card.head,incomingNode,incoming.head);if(!this.closed)this.update=update;});}
 async saveCard(title:string,notes:string){const node=this.cardNode,card=this.card;if(!node||!card)return;await this.run(async()=>{await this.api.saveCorporateCard(this.project,node,card.head,title,notes);if(this.closed)return;this.card=await this.api.readCorporateCard(this.project,node);if(!this.closed)this.notice="Карточка сохранена.";});}
 async followCardLink(index:number){const card=this.card,node=this.cardNode;if(!card||!node)return;await this.run(async()=>{const target=await this.api.resolveCorporateCardLink(this.project,node,card.head,index);if(this.closed)return;if(!target.node_id){this.notice="Связанная карточка недоступна или не определена однозначно.";return;}const next=await this.api.readCorporateCard(this.project,target.node_id);if(!this.closed){this.cardNode=target.node_id;this.card=next;this.pendingUpdate=undefined;}});}
 async readAccess(node=this.cardNode||this.pending?.node_id,cursor=""){if(!node)return;await this.run(async()=>{const doc=await this.api.readDraftDocument(this.project,node);if(this.closed)return;const page=await this.api.listPrivateDraftParticipants(this.project,node,doc.head,cursor);if(!this.closed)this.access={node,name:doc.terms?.[0]?.metadata?.name||node,page};});}
 async changeAccess(principal:string,mode:PrivateParticipantMode){const access=this.access,person=access?.page.participants.find(p=>p.principal_id===principal);if(!access||!person)return;await this.run(async()=>{await this.api.setPrivateDraftParticipant(this.project,access.node,access.page.head,principal,person.mode,mode);if(this.closed)return;const doc=await this.api.readDraftDocument(this.project,access.node);if(this.closed)return;const page=await this.api.listPrivateDraftParticipants(this.project,access.node,doc.head,"");if(!this.closed){this.access={node:access.node,name:doc.terms?.[0]?.metadata?.name||access.node,page};this.notice="Доступ к карточке обновлён.";}});}
 async previewWorkflow(plan:string){const source=this.result;if(!source)return;await this.run(async()=>{const result=await this.api.previewCorporateWorkflow(this.project,source.source_node_id,source.source_head,this.provider==="jira"?"jira":"bitrix24",JSON.parse(plan));if(!this.closed){this.workflow=result;this.workflowPlan=JSON.parse(plan);this.workflowPending=undefined;}});}
 async prepareWorkflow(confirmed:boolean){const shown=this.workflow,plan=this.workflowPlan;if(!shown||!plan)return;await this.run(async()=>{const pending=await this.api.prepareSharedCorporateWorkflow(this.project,shown,plan,confirmed);if(!this.closed)this.workflowPending=pending;});}
 async createWorkflow(){const pending=this.workflowPending;if(!pending)return;this.workflowPending={...pending,state:"unconfirmed"};await this.run(async()=>{const result=await this.api.executeSharedCorporateWorkflow(pending.id);if(!this.closed)this.workflowPending=result;});}
 async readLinks(node=this.pending?.node_id,task?:string){if(!node)return;this.linkReturn=undefined;await this.run(async()=>{const doc=await this.api.readDraftDocument(this.project,node);if(this.closed)return;if(!doc.exists||doc.conflicted)throw Error("Unavailable copy");const value=await this.api.readJiraLinks(this.project,node,doc.head);if(task)value.links=value.links.filter(ref=>ref.source_task_id===task);if(!this.closed)this.links={node,head:doc.head,name:doc.terms?.[0]?.metadata?.name||node,task,value};});}
 async returnToTask(){const target=this.linkReturn;this.linkReturn=undefined;if(!target||target.project!==this.project)return;await this.readLinks(target.node,target.task);}

 async followLink(index:number){const links=this.links,ref=links?.value.links[index];if(!links||!ref)return;await this.run(async()=>{const target=await this.api.resolveCorporateTarget(this.project,links.node,links.head,ref.kind,ref.entity_id);if(this.closed)return;if(!target.node_id){this.notice="Связанный объект недоступен, ещё не перенесён или найдено несколько копий.";return;}const doc=await this.api.readDraftDocument(this.project,target.node_id);if(this.closed)return;if(!doc.exists||doc.conflicted||doc.head!==links.head)throw Error("Changed target");const value=await this.api.readJiraLinks(this.project,target.node_id,doc.head);if(!this.closed){if(ref.source_task_id)this.linkReturn={project:this.project,node:links.node,task:ref.source_task_id};this.links={node:target.node_id,head:doc.head,name:doc.terms?.[0]?.metadata?.name||target.node_id,value};}});}
 async openTaskInTracker(index:number,node:string){const current=this.links,ref=current?.value.links[index];if(!current||!node||ref?.kind!=="task")return;this.linkReturn=undefined;await this.run(async()=>{
 const source=await this.api.readDraftDocument(this.project,current.node);if(this.closed)return;if(!source.exists||source.conflicted)throw Error("Unavailable source");
 const sourceLinks=await this.api.readJiraLinks(this.project,current.node,source.head);if(this.closed)return;if(!sourceLinks.links.some(link=>link.kind==="task"&&link.entity_id===ref.entity_id))throw Error("Changed relation");
 const origin=await this.api.readCorporateOrigin(this.project,current.node,source.head);if(this.closed)return;
 const target=await this.api.readDraftDocument(this.project,node);if(this.closed)return;if(!target.exists||target.conflicted||target.head!==source.head)throw Error("Unavailable tracker");
 const targetOrigin=await this.api.readCorporateOrigin(this.project,node,target.head);if(this.closed)return;
 if(!origin||!targetOrigin||targetOrigin.entity_kind!=="task"||!targetOrigin.entity_id.startsWith("workflow:")||origin.provider!==targetOrigin.provider||origin.source_node_id!==targetOrigin.source_node_id||origin.source_sha256!==targetOrigin.source_sha256)throw Error("Different import source");
 const task=origin.provider==="bitrix24"&&ref.entity_id.startsWith("task:")?ref.entity_id.slice(5):origin.provider==="jira"?ref.entity_id:"";if(!task)throw Error("Invalid source task");
 const value=await this.api.readJiraLinks(this.project,node,target.head);if(this.closed)return;value.links=value.links.filter(link=>link.source_task_id===task);if(!value.links.length)throw Error("Task not present in selected tracker");
 const confirmed=await this.api.readCorporateOrigin(this.project,current.node,source.head);if(this.closed)return;if(!confirmed||confirmed.provider!==origin.provider||confirmed.source_node_id!==origin.source_node_id||confirmed.source_sha256!==origin.source_sha256)throw Error("Changed source origin");
 this.links={node,head:target.head,name:target.terms?.[0]?.metadata?.name||node,task,value};
 });}
 async readOrigin(){const node=this.pending?.node_id;if(!node)return;await this.run(async()=>{const doc=await this.api.readDraftDocument(this.project,node);if(this.closed)return;const origin=await this.api.readCorporateOrigin(this.project,node,doc.head);if(!this.closed)this.origin=origin;});}
 render(){if(this.closed)return;this.root.replaceChildren();const text=(s:string,tag="p")=>{const e=document.createElement(tag);e.textContent=s;this.root.append(e);};const button=(label:string,fn:()=>void)=>{const b=document.createElement("button");b.textContent=label;b.disabled=this.busy;b.onclick=fn;this.root.append(b);return b;};
 const label=this.provider==="jira"?"Jira":"Bitrix24";text(`Перенос из ${label}`,"h2");button(`Закрыть перенос из ${label}`,()=>{this.closed=true;this.result=undefined;this.page=undefined;this.root.replaceChildren();this.close();}).disabled=false;
 text(this.provider==="bitrix"?"Предпросмотр JSON-выгрузки Bitrix24: задачи, компании, контакты, сотрудники и отделы. Можно создать отдельную приватную JSON-карточку клиента, сотрудника или отдела; для задач доступно явное сопоставление статуса и исполнителя. Формат mnemos.bitrix24-export, версия 1; максимум 4 МиБ.":"Предпросмотр ранее загруженной JSON-выгрузки Jira. Можно создать отдельную новую задачу для разбора записи. Статус и исполнитель сопоставляются явно; внешние права требуют отдельного решения. Формат: mnemos.jira-search-export, версия 1; максимум 4 МиБ.");
 const select=document.createElement("select");select.setAttribute("aria-label",`Проект выгрузки ${label}`);select.disabled=this.busy;for(const p of [{id:"",name:"Выберите проект"},...this.projects]){const o=document.createElement("option");o.value=p.id;o.textContent=p.name;select.append(o);}select.value=this.project;select.onchange=()=>{if(select.value)void this.load(select.value);else{this.project="";this.linkReturn=undefined;this.workflow=undefined;this.workflowPlan=undefined;this.workflowPending=undefined;this.links=undefined;this.page=undefined;this.result=undefined;this.card=undefined;this.update=undefined;this.pendingUpdate=undefined;this.pending=undefined;this.origin=undefined;this.access=undefined;this.render();}};this.root.append(select);
 if(this.project)button(`Обновить выгрузки ${label}`,()=>void this.load(this.project));
 if(this.notice)text(this.notice);if(this.busy)text("Чтение…");
 for(const row of this.page?.documents??[])if(row.content_type==="application/json"&&!row.conflicted)button(`Проверить выгрузку: ${row.name}`,()=>void this.preview(row.node_id));
 for(const row of this.page?.documents??[])if(row.content_type==="application/vnd.mnemos.task-tracker+json"&&!row.conflicted)button(`Связи задач: ${row.name}`,()=>void this.readLinks(row.node_id));
 if(this.page?.next_cursor)button("Следующая страница документов",()=>void this.load(this.project,this.page!.next_cursor));
 if(this.mapping){const m=this.mapping;text(`Сопоставление задачи: ${m.title}`,"h3");text(`Исходный статус: ${m.source.status}; внешний исполнитель: ${m.source.responsible_id||"не указан"}.`);
 const status=document.createElement("select");status.setAttribute("aria-label","Статус задачи Mnemos");for(const [value,label] of [["","Выберите статус"],["todo","К выполнению"],["in_progress","В работе"],["blocked","Заблокирована"],["done","Выполнена"],["cancelled","Отменена"]]){const o=document.createElement("option");o.value=value;o.textContent=label;status.append(o);}this.root.append(status);
 const fields:Record<string,HTMLInputElement>={};for(const [key,label] of [["assignee_id","Исполнитель Mnemos (ID)"],["stage_name","Название этапа"],["department","Отдел"],["next_step","Следующий шаг"],["blocker","Причина блокировки"],["result","Результат или причина отмены"]]){const e=document.createElement("input");e.setAttribute("aria-label",label);e.placeholder=label;fields[key]=e;this.root.append(e);}
 text("Создание предоставит выбранному исполнителю (для агента — его владельцу) чтение новой задачи. Исходная выгрузка останется под отдельными правами. Подготовка требует подтверждения создания следующим шагом.");
 button("Подготовить назначенную задачу",()=>void this.prepareMapped({source_record_sha256:m.source.record_sha256,source_status:m.source.status,source_responsible_id:m.source.responsible_id,status:status.value,assignee_id:fields.assignee_id.value,stage_name:fields.stage_name.value,department:fields.department.value,next_step:fields.next_step.value,blocker:fields.blocker.value,result:fields.result.value}));
 }
 if(this.pending){text(`Заявка: ${this.pending.name}`);if(this.pending.assignment)text(`Статус: ${this.pending.assignment.status}; исполнитель Mnemos: ${this.pending.assignment.assignee||"не назначен"}. При создании выбранному исполнителю будет предоставлено чтение задачи.`);if(this.pending.state==="created"){text(this.pending.document?`Документ создан: ${this.pending.node_id}.`:this.pending.assignment?`Назначенная задача создана: ${this.pending.node_id}.`:this.provider==="bitrix"?`Карточка создана: ${this.pending.node_id}. Права и рабочие связи сопоставляются отдельно.`:`Задача для разбора создана: ${this.pending.node_id}. Публикация и назначение исполнителя выполняются отдельно.`);button("Проверить происхождение задачи",()=>void this.readOrigin());button("Связи созданного объекта",()=>void this.readLinks());if(this.provider==="bitrix"||this.pending.document||this.pending.assignment){if(!this.pending.assignment&&!this.pending.document)button("Открыть карточку",()=>void this.readCard());button("Доступ к созданной карточке",()=>void this.readAccess(this.pending?.node_id));}}else{text(this.pending.document?"Будет создан отдельный приватный файл с исходными байтами. DOCX/XLSX можно затем преобразовать через существующий офисный импорт. Связи и внешние права остаются в записи источника.":this.pending.assignment?"Будет создан трекер с выбранным статусом и исполнителем. Полная исходная запись сохранится в описании задачи.":this.provider==="bitrix"?"Будет создана приватная JSON-карточка с полной исходной записью и внешними связями. Учётные записи и права не создаются.":"Будет создана новая приватная todo-задача без исполнителя, с полной исходной записью в описании. Это не перенос исходного статуса и прав.");button(this.pending.state==="unconfirmed"?`Проверить и повторить ту же заявку ${label}`:this.pending.document?"Подтвердить создание документа":this.pending.assignment?"Подтвердить создание назначенной задачи":this.provider==="bitrix"?"Подтвердить создание карточки":"Подтвердить создание задачи для разбора",()=>void this.confirm());}}
 if(this.links){const selected=this.links;text(`Связанный объект: ${selected.name}`,"h3");text(`Узел: ${selected.node}`);if(selected.task){text(`Связи исходной задачи ${selected.task}`);button("Все связи общего трекера",()=>void this.readLinks(selected.node));}if(this.linkReturn)button(`Вернуться к связям задачи ${this.linkReturn.task} общего трекера`,()=>void this.returnToTask());text("Связи восстановлены по исходной выгрузке. Каждый переход отдельно проверяет доступ к источнику и цели.");button("Обновить связи",()=>void this.readLinks(selected.node,selected.task));button("Доступ к связанному объекту",()=>void this.readAccess(selected.node));if(!selected.value.links.length)text("Связей в исходной записи нет.");for(const [index,ref] of selected.value.links.entries()){button(`Перейти к связанному объекту: ${ref.label}`,()=>void this.followLink(index));if(ref.kind==="task"){
 const choice=document.createElement("select");choice.setAttribute("aria-label",`Трекер для задачи ${ref.entity_id}`);choice.disabled=this.busy;const empty=document.createElement("option");empty.value="";empty.textContent="Выберите общий трекер";choice.append(empty);
 for(const row of this.page?.documents??[])if(row.content_type==="application/vnd.mnemos.task-tracker+json"&&!row.conflicted){const option=document.createElement("option");option.value=row.node_id;option.textContent=`${row.name} · ${row.node_id}`;choice.append(option);}this.root.append(choice);
 const open=button(`Открыть задачу ${ref.entity_id} в выбранном трекере`,()=>void this.openTaskInTracker(index,choice.value));open.disabled=true;choice.onchange=()=>{open.disabled=this.busy||!choice.value;};
 }}}
 if(this.card){text(`Карточка: ${this.card.kind}`,"h3");button("Доступ к открытой карточке",()=>void this.readAccess(this.cardNode));const title=document.createElement("input"),notes=document.createElement("textarea");title.setAttribute("aria-label","Название карточки");notes.setAttribute("aria-label","Заметки карточки");title.value=this.card.title;notes.value=this.card.notes;title.disabled=notes.disabled=this.busy;this.root.append(title,notes);text("Изменяются название и заметки; исходные поля и внешние связи сохраняются.");button("Сохранить карточку",()=>void this.saveCard(title.value,notes.value));const incoming=document.createElement("select");incoming.setAttribute("aria-label","Новая выгрузка для обновления карточки");incoming.disabled=this.busy;const placeholder=document.createElement("option");placeholder.value="";placeholder.textContent="Выберите новую выгрузку";incoming.append(placeholder);for(const row of this.page?.documents??[])if(row.node_id!==this.cardNode&&row.content_type==="application/json"&&!row.conflicted){const option=document.createElement("option");option.value=row.node_id;option.textContent=row.name;incoming.append(option);}this.root.append(incoming);text("Сравнение использует сохранённую карточку. Сначала сохраните введённые правки.");button("Проверить обновление карточки",()=>void this.previewUpdate(incoming.value));for(const [index,ref] of this.card.references.entries())button(`Перейти: ${ref.field} → ${ref.kind} ${ref.id}`,()=>void this.followCardLink(index));}
 if(this.update){const p=this.update.plan;text("Предпросмотр обновления карточки","h3");text(p.source_changed?"Исходная запись изменилась.":"Исходная запись не изменилась.");text(p.local_changed?"Есть локальные правки; заметки сохраняются.":"Локальных правок нет.");for(const conflict of p.conflicts){text(`Конфликт: ${conflict.field}`);text(`Ранее: ${conflict.base}`);text(`В карточке: ${conflict.local}`);text(`В новой выгрузке: ${conflict.incoming}`);if(conflict.field==="title"){button("Сохранить локальное название в плане",()=>void this.resolveUpdate("local"));button("Принять название источника в плане",()=>void this.resolveUpdate("incoming"));}}if(!p.conflicts.length)text(this.update.resolution?`Конфликт разрешён: ${this.update.resolution.title_choice==="local"?"сохранить локальное название":"принять название источника"}.`:"Конфликтов не найдено.");text("Это только сравнение. Обновление карточки ещё не применено.");if(p.source_changed&&!p.conflicts.length&&p.content)button("Подготовить обновление карточки",()=>void this.prepareUpdate());}
 if(this.pendingUpdate){const pending=this.pendingUpdate;if(pending.state==="updated"){text("Карточка обновлена. Происхождение новой версии сохранено.");button("Проверить повтор обновления",()=>void this.applyUpdate());}else{ text("Подготовлено обновление существующей карточки. Название берётся из выбранного варианта, заметки сохраняются.");button(pending.state==="unconfirmed"?"Проверить и повторить то же обновление":"Подтвердить обновление карточки",()=>void this.applyUpdate());}}
 if(this.access){const access=this.access;text(`Участники карточки: ${access.name}`,"h3");text("Выберите пользователя Mnemos и доступ только к этой карточке. Исходная выгрузка и связанные карточки требуют отдельного доступа.");if(!access.page.participants.length)text("Нет доступных участников на этой странице. Для приглашения нужны права пользователя на папку карточки.");for(const person of access.page.participants){text(`${person.display_name||person.principal_id} (${person.principal_id}): ${person.mode||"нет приглашения"}`);if(person.can_read&&person.mode!=="read")button(`Чтение: ${person.principal_id}`,()=>void this.changeAccess(person.principal_id,"read"));if(person.can_write&&person.mode!=="write")button(`Редактирование: ${person.principal_id}`,()=>void this.changeAccess(person.principal_id,"write"));if(person.mode)button(`Отозвать: ${person.principal_id}`,()=>void this.changeAccess(person.principal_id,""));}button("Обновить участников карточки",()=>void this.readAccess(access.node));if(access.page.next_cursor)button("Следующая страница участников",()=>void this.readAccess(access.node,access.page.next_cursor));}
 if(this.origin===null)text("Для этой задачи нет записи происхождения импорта.");else if(this.origin){const o=this.origin;text(`Происхождение: ${o.provider} · ${o.entity_kind} · ${o.entity_id}`);text(`Исходный документ: ${o.source_node_id}; версия: ${o.source_head}`);text(`SHA-256 исходника: ${o.source_sha256}; ${o.revision_head?"результата обновления":"первоначального результата"}: ${o.output_sha256}`);text(o.revision_head?`Происхождение обновления версии: ${o.revision_head}. Последующие правки проверяются по истории.`:"Это происхождение первоначального импорта. Последующие правки задачи проверяются по её истории.");}
 if(this.workflow){text("План общего трекера проверен","h3");text("Проверены зависимости, статусы и переходы этапов. Это предпросмотр: общий трекер ещё не сохранён, доступ исполнителям не выдан.");text(`SHA-256 результата: ${this.workflow.sha256}`);const label=document.createElement("label"),consent=document.createElement("input");consent.type="checkbox";consent.setAttribute("aria-label","Общий доступ исполнителям");label.append(consent,document.createTextNode("Все выбранные исполнители (для агентов — их владельцы) смогут читать весь трекер со всеми исходными записями задач."));this.root.append(label);button("Подготовить общий трекер",()=>void this.prepareWorkflow(consent.checked));const pre=document.createElement("pre");pre.textContent=this.workflow.content;this.root.append(pre);}
 if(this.workflowPending){const pending=this.workflowPending;if(pending.state==="created"){text(`Общий трекер создан: ${pending.node_id}.`);button("Доступ к общему трекеру",()=>void this.readAccess(pending.node_id));button("Связи задач общего трекера",()=>void this.readLinks(pending.node_id));}else{ text("Общий трекер подготовлен. При создании выбранные исполнители получат чтение всего артефакта; исходная выгрузка остаётся под отдельными правами.");button(pending.state==="unconfirmed"?"Проверить и повторить создание общего трекера":"Подтвердить создание общего трекера",()=>void this.createWorkflow());}}
 if(!this.result)return;
 text("Общий трекер с зависимостями","h3");text("План mnemos.corporate-workflow-plan задаёт задачи с хешами исходных записей, сопоставление статусов и исполнителей, зависимости по ID задач источника и переходы между этапами. Внешние ссылки не становятся зависимостями автоматически.");const workflowPlan=document.createElement("textarea");workflowPlan.setAttribute("aria-label","План общего трекера (JSON)");this.root.append(workflowPlan);button("Проверить план общего трекера",()=>void this.previewWorkflow(workflowPlan.value));

 if("records" in this.result.preview){const p=this.result.preview;
 text(`Записей: ${p.records.length}. Связей вне выборки: ${p.references.filter(r=>!r.resolved).length}.`);
 text("Права не сопоставлены. Импорт не выполнен. Полнота данных организации не подтверждена.");
 text(`Источник: ${p.source_id}; версия: ${this.result.source_head}; SHA-256: ${this.result.source_sha256}`);
 text(`Отсутствующие коллекции: ${p.missing_collections.join(", ")}`);
 for(const row of p.records){if(row.kind==="file"){const file=p.files?.find(f=>f.object_id===row.id);text(file?.available?`Файл: ${file.size_bytes} байт; содержимое включено в выгрузку.`:"Содержимого файла нет в выгрузке.");if(file?.available)button(`Подготовить документ: ${row.id}`,()=>void this.prepareRecord("file",row.id));}if(row.kind==="task"&&row.task_mapping_source)button(`Сопоставить задачу: ${row.id}`,()=>this.startMapping(row.id));if(["company","contact","person","department"].includes(row.kind))button(`Подготовить карточку: ${row.kind} ${row.id}`,()=>void this.prepareRecord(row.kind,row.id));text(`${row.kind} ${row.id} — ${row.title}`,"h3");if(row.missing_fields.length)text(`Поля отсутствуют: ${row.missing_fields.join(", ")}`);const detail=document.createElement("details"),summary=document.createElement("summary"),pre=document.createElement("pre");summary.textContent="Исходные поля записи";pre.textContent=row.record;detail.append(summary,pre);this.root.append(detail);}
 for(const ref of p.references)if(ref.resolved&&ref.from_kind==="person"&&ref.to_kind==="department"&&ref.field==="UF_DEPARTMENT")button(`Сопоставить сотрудника ${ref.from_id} с отделом ${ref.to_id}`,()=>this.openDepartment(ref.from_id,ref.to_id));
 for(const ref of p.references)text(`${ref.from_kind} ${ref.from_id}: ${ref.field} → ${ref.to_kind} ${ref.to_id} (${ref.resolved?"есть в выборке":"отсутствует в выборке"})`);
 return;
 }const p=this.result.preview;
 text(`Задач: ${p.issues.length}. Связей вне выборки: ${p.unresolved.length}. Вложений без содержимого: ${p.pending_attachments}.`);
 text("Права не сопоставлены. Импорт не выполнен. Исходные поля сохранены в предпросмотре; полнота данных организации не подтверждена.");
 text(`Источник: ${p.source_id}; версия: ${this.result.source_head}; SHA-256: ${this.result.source_sha256}`);
 for(const issue of p.issues){if(issue.task_mapping_source)button(`Сопоставить задачу: ${issue.key}`,()=>this.startMapping(issue.id));for(const file of p.attachments?.filter(a=>a.issue_id===issue.id)??[]){text(`Вложение ${file.id}: ${file.name} (${file.available?"содержимое включено":"нет содержимого"})`);if(file.available)button(`Подготовить вложение: ${issue.key} / ${file.id}`,()=>void this.prepareAttachment(issue.id,file.id));}button(`Подготовить задачу для разбора: ${issue.key}`,()=>void this.prepare(issue.id));text(`${issue.key} — ${issue.title}`,"h3");if(issue.missing_fields.length)text(`Поля отсутствуют: ${issue.missing_fields.join(", ")}`);if(issue.referenced_issues.length)text(`Связанные задачи источника: ${issue.referenced_issues.join(", ")}`);const detail=document.createElement("details"),summary=document.createElement("summary"),pre=document.createElement("pre");summary.textContent="Исходные поля задачи";pre.textContent=issue.record;detail.append(summary,pre);this.root.append(detail);}
 for(const ref of p.unresolved)text(`Задача ${ref.from} ссылается на ${ref.to}, отсутствующую в выборке.`);
 }
}
