import type {MnemosAccountSession} from "../src/account-session.ts";
import type {DatabaseConnection,DatabaseRegistration} from "../src/database-connections.ts";
type API=Pick<MnemosAccountSession,"listVisibleDatabaseConnections"|"listDatabaseConnections"|"registerDatabaseConnection"|"removeDatabaseConnection">;
export class DatabaseConnectionsView {
 private visible?:{databases:DatabaseConnection[];truncated:boolean};
 private project="";private rows?:DatabaseConnection[];private busy=false;private closed=false;private notice="";private pending?:{project:string;input:DatabaseRegistration}|{project:string;remove:string};
 constructor(private root:HTMLElement,private api:API,private projects:ReadonlyArray<{id:string;name:string}>,private close:()=>void){}
 private async run(work:()=>Promise<void>){if(this.closed||this.busy)return;this.busy=true;this.notice="";this.render();try{await work();}catch{this.visible=undefined;this.rows=undefined;this.pending=undefined;this.notice="Действие не подтверждено. Обновите список перед повтором; проверьте права проекта и подготовку подключения.";}finally{this.busy=false;if(!this.closed)this.render();}}
 async discover(){await this.run(async()=>{this.visible=undefined;const out=await this.api.listVisibleDatabaseConnections();if(!this.closed)this.visible=out;});}
 async load(project:string){await this.run(async()=>{this.project=project;this.rows=undefined;this.pending=undefined;const out=await this.api.listDatabaseConnections(project);if(!this.closed)this.rows=out.databases;});}
 prepare(input:DatabaseRegistration){if(this.busy||this.closed||!this.project)return;if(!input.name.trim()||!/^MNEMOS_DB_[A-Z0-9_]+$/.test(input.env_var)||!Number.isSafeInteger(input.max_rows)||input.max_rows<1||!Number.isSafeInteger(input.timeout_ms)||input.timeout_ms<1){this.pending=undefined;this.notice="Укажите имя, ссылку подготовленного ключа и положительные целые ограничения.";this.render();return;}this.pending={project:this.project,input:{...input}};this.render();}
 async confirm(){const pending=this.pending;if(!pending)return;await this.run(async()=>{this.pending=undefined;let message:string;if("input" in pending){const out=await this.api.registerDatabaseConnection(pending.project,pending.input);message=out.database.configured?"Подключение сохранено; ключ подготовлен для этого проекта.":"Запись сохранена, но ключ для этого проекта недоступен. Нужна настройка оператором.";}else{const out=await this.api.removeDatabaseConnection(pending.project,pending.remove);message=out.removed?"Подключение снято с проекта.":"Подключение уже отсутствует.";}const out=await this.api.listDatabaseConnections(pending.project);if(!this.closed){this.rows=out.databases;this.notice=message;}});}
 render(){if(this.closed)return;this.root.replaceChildren();const text=(s:string,tag="p")=>{const e=document.createElement(tag);e.textContent=s;this.root.append(e);};const button=(s:string,fn:()=>void)=>{const b=document.createElement("button");b.textContent=s;b.disabled=this.busy;b.onclick=fn;this.root.append(b);return b;};const input=(label:string,value="",type="text")=>{const l=document.createElement("label");l.textContent=label;const i=document.createElement("input");i.setAttribute("aria-label",label);i.type=type;i.value=value;i.disabled=this.busy;l.append(i);this.root.append(l);return i;};
 text("Подключения БД","h2");button("Закрыть подключения БД",()=>{this.closed=true;this.rows=undefined;this.pending=undefined;this.root.replaceChildren();this.close();}).disabled=false;
 text("Ключ готовит оператор для конкретного проекта. Здесь сохраняется только ссылка на него. Снятие подключения не изменяет внешнюю БД.");
 const select=document.createElement("select");select.setAttribute("aria-label","Проект подключения БД");select.disabled=this.busy;for(const p of [{id:"",name:"Выберите проект"},...this.projects]){const option=document.createElement("option");option.value=p.id;option.textContent=p.name;select.append(option);}select.value=this.project;this.root.append(select);select.onchange=()=>{if(select.value)void this.load(select.value);else{this.project="";this.rows=undefined;this.pending=undefined;this.render();}};
 button("Мои доступные подключения БД",()=>void this.discover());for(const row of this.visible?.databases??[])button(`Открыть ${row.name} · проект ${row.project_id}`,()=>void this.load(row.project_id));if(this.visible?.truncated)text("Показана часть подключений. Нужный проект можно открыть по ID.");const projectID=input("ID проекта БД");button("Открыть проект БД по ID",()=>void this.load(projectID.value));
 if(this.notice)text(this.notice);if(this.busy)text("Выполняется…");if(!this.project)return;
 button("Обновить подключения БД",()=>void this.load(this.project));
 for(const row of this.rows??[]){text(`${row.name} · ${row.driver}`,"h3");text(`Ссылка: ${row.env_var} · ${row.configured?"ключ подготовлен":"ключ недоступен для проекта"}`);text(`Настроил: ${row.registered_by} · ${row.registered_at}`);if(row.unreachable_since)text(`Недоступно с: ${row.unreachable_since}`);button(`Снять подключение: ${row.name}`,()=>{this.pending={project:this.project,remove:row.name};this.render();});}
 text("Настроить подключение PostgreSQL","h3");const name=input("Имя БД в проекте"),ref=input("Ссылка на подготовленный ключ"),limit=input("Максимум строк","200","number"),timeout=input("Срок запроса, мс","10000","number");
 button("Подготовить подключение",()=>this.prepare({name:name.value,driver:"postgres",env_var:ref.value,max_rows:Number(limit.value),timeout_ms:Number(timeout.value)}));
 if(this.pending){const p=this.pending;text("input" in p?`Сохранить ${p.input.name} → ${p.input.env_var}; максимум ${p.input.max_rows} строк, ${p.input.timeout_ms} мс. Настройки одноимённого подключения будут заменены.`:`Снять ${p.remove} с проекта?`);button("Подтвердить настройку БД",()=>void this.confirm());button("Отменить настройку БД",()=>{this.pending=undefined;this.render();});}
 }
}
