import type {MnemosAccountSession} from "../src/account-session.ts";
import type {GitFile,GitCommit,GitConnection,GitConnectionPage,GitRepositoryPage,GitSetup,GitProjectRepositoryPage,GitRepositorySelection} from "../src/git-connections.ts";
import type {GitRegistrationIntent} from "../src/git-registration.ts";
type API=Pick<MnemosAccountSession,"readGitFile"|"readGitCommit"|"readOwnedGitBinding"|"bindGitRepository"|"readGitConnection"|"disableGitConnection"|"listGitRegistrationIntents"|"saveGitRegistrationIntent"|"inspectGitRegistrationIntent"|"executeGitRegistrationIntent"> & {listProjectGitRepositories:(project:string,cursor:string)=>ReturnType<MnemosAccountSession["listProjectGitRepositories"]>;listGitConnections:(cursor:string)=>ReturnType<MnemosAccountSession["listGitConnections"]>;listGitRepositories:(id:string,page:number)=>ReturnType<MnemosAccountSession["listGitRepositories"]>};
export class GitConnectionsView {
 private file?:GitFile;
 private push?:{url:string;resource:string;name:string};
 private commit?:{project:string;connection:string;ref:string;value:GitCommit};
 private project="";private bindings?:GitProjectRepositoryPage;private bindingIntent?:{project:string;connection:string;repository:string;input:GitRepositorySelection};
 private busy=false;private closed=false;private notice="";private page?:GitConnectionPage;private intents:GitRegistrationIntent[]=[];private intent?:GitRegistrationIntent;private selected?:GitConnection;private repositories?:GitRepositoryPage;private disable?:{id:string;revision:number};
 constructor(private root:HTMLElement,private api:API,private close:()=>void,private projects:ReadonlyArray<{id:string;name:string}>=[]){}
 private async run(work:()=>Promise<void>){if(this.busy||this.closed)return;this.busy=true;this.push=undefined;this.notice="";this.render();try{await work();}catch{this.file=undefined;this.commit=undefined;this.bindings=undefined;this.bindingIntent=undefined;this.page=undefined;this.selected=undefined;this.repositories=undefined;this.notice="Действие не подтверждено. Проверьте состояние подключения или повторите сохранённую заявку.";}finally{this.busy=false;if(!this.closed)this.render();}}
 async loadProject(project:string,cursor=""){await this.run(async()=>{this.file=undefined;this.commit=undefined;this.project=project;this.bindings=undefined;this.bindingIntent=undefined;const page=await this.api.listProjectGitRepositories(project,cursor);if(!this.closed)this.bindings=page;});}
 async preparePush(project:string,connection:string,repository:string){await this.run(async()=>{const state=await this.api.readOwnedGitBinding(project,connection,repository);if(!state.binding?.enabled||!state.push_url||!state.mcp_resource)throw Error("Push route unavailable");if(!this.closed)this.push={url:state.push_url,resource:state.mcp_resource,name:state.binding.repository_name};});}
 async readFile(path:string){const c=this.commit;if(!c)return;await this.run(async()=>{this.file=undefined;const value=await this.api.readGitFile(c.project,c.connection,c.value.repository_id,c.value.sha,path);if(!this.closed)this.file=value;});}
 async readCommit(project:string,connection:string,repository:string,ref:string){await this.run(async()=>{this.file=undefined;this.commit=undefined;const value=await this.api.readGitCommit(project,connection,repository,ref);if(!this.closed)this.commit={project,connection,ref,value};});}
 async prepareBinding(project:string,connection:string,repository:string,name:string,enabled:boolean){await this.run(async()=>{this.bindingIntent=undefined;const state=await this.api.readOwnedGitBinding(project,connection,repository);if(!enabled&&!state.binding)throw Error("Missing binding");if(!this.closed)this.bindingIntent={project,connection,repository,input:{expected_connection_revision:state.connection_revision,expected_revision:state.binding?.revision??0,repository_name:enabled?name:state.binding!.repository_name,enabled}};});}
 async confirmBinding(){const intent=this.bindingIntent;if(!intent)return;await this.run(async()=>{this.file=undefined;this.commit=undefined;this.bindingIntent=undefined;await this.api.bindGitRepository(intent.project,intent.connection,intent.repository,intent.input);this.bindings=await this.api.listProjectGitRepositories(intent.project,"");this.notice=intent.input.enabled?"Репозиторий связан с проектом.":"Привязка репозитория отключена.";});}
 async load(cursor=""){await this.run(async()=>{this.page=undefined;this.selected=undefined;this.repositories=undefined;this.disable=undefined;const page=await this.api.listGitConnections(cursor),intents=await this.api.listGitRegistrationIntents();if(!this.closed){this.page=page;this.intents=intents;this.intent=undefined;}});}
 async save(setup:GitSetup){await this.run(async()=>{const intent=await this.api.saveGitRegistrationIntent(setup);if(!this.closed){this.intent=intent;this.intents=await this.api.listGitRegistrationIntents();}});}
 async submit(id:string,token:string,retry:boolean){await this.run(async()=>{
  if(this.intent?.id===id)this.intent={...this.intent,attempted:true};this.intents=this.intents.map(e=>e.id===id?{...e,attempted:true}:e);
  const result=await this.api.executeGitRegistrationIntent(id,token,retry);token="";
  if(!this.closed){this.selected=result;this.repositories=undefined;this.intents=await this.api.listGitRegistrationIntents();this.intent=this.intents.find(e=>e.id===id);this.page=await this.api.listGitConnections("");this.notice="Подключение подтверждено. Выберите репозиторий для работы.";}
 });}
 async inspect(id:string){await this.run(async()=>{this.selected=undefined;this.repositories=undefined;const c=await this.api.inspectGitRegistrationIntent(id);if(!this.closed){this.selected=c;this.intents=await this.api.listGitRegistrationIntents();this.intent=this.intents.find(e=>e.id===id);this.page=await this.api.listGitConnections("");}});}
 async open(id:string,page=1){await this.run(async()=>{this.selected=undefined;this.repositories=undefined;this.disable=undefined;const c=await this.api.readGitConnection(id);let repositories:GitRepositoryPage|undefined;let unavailable=false;if(c.enabled){try{repositories=await this.api.listGitRepositories(id,page);}catch{unavailable=true;}}const current=await this.api.readGitConnection(id);if(current.revision!==c.revision||current.enabled!==c.enabled)throw Error("Git connection changed");if(!this.closed){this.selected=current;this.repositories=repositories;if(unavailable)this.notice="Каталог недоступен. Подключение можно отключить.";}});}
 async confirmDisable(){const pending=this.disable;if(!pending)return;await this.run(async()=>{this.file=undefined;this.commit=undefined;this.disable=undefined;this.repositories=undefined;const result=await this.api.disableGitConnection(pending.id,pending.revision);if(!this.closed){this.selected=result.connection;this.page=await this.api.listGitConnections("");this.notice=result.credential_removed?"Подключение отключено, ключ удалён.":"Доступ отозван. Удаление файла ключа нужно повторить.";}});}
 render(){if(this.closed)return;this.root.replaceChildren();const section=document.createElement("section");this.root.append(section);
  const text=(value:string,tag="p")=>{const e=document.createElement(tag);e.textContent=value;section.append(e);return e;};
  const button=(label:string,click:()=>void)=>{const e=document.createElement("button");e.textContent=label;e.disabled=this.busy;e.addEventListener("click",click);section.append(e);return e;};
  const input=(label:string,type="text",value="")=>{const holder=document.createElement("label");holder.textContent=label;const field=document.createElement("input");field.type=type;field.value=value;field.setAttribute("aria-label",label);field.disabled=this.busy;if(type==="password"){field.autocomplete="off";field.spellcheck=false;}holder.append(field);section.append(holder);return field;};
  text("Git-подключения","h2");text("Собственные GitHub/GitLab аккаунты. Подключение аккаунта само по себе не выдаёт проекту доступ к репозиториям.");
  button("Закрыть Git-подключения",()=>{this.closed=true;this.root.replaceChildren();this.close();});button("Обновить подключения",()=>void this.load());
  if(this.notice)text(this.notice);if(this.busy)text("Выполняется…");
  for(const c of this.page?.connections??[])button(`${c.enabled?"Активно":"Отключено"}: ${c.name} (${c.account_login})`,()=>void this.open(c.connection_id));
  if(this.page?.next_cursor)button("Следующие подключения",()=>void this.load(this.page!.next_cursor!));
  text("Репозитории проекта","h3");const project=document.createElement("select");project.setAttribute("aria-label","Проект для репозиториев");project.disabled=this.busy;const empty=document.createElement("option");empty.value="";empty.textContent="Выберите проект";project.append(empty);for(const p of this.projects){const option=document.createElement("option");option.value=p.id;option.textContent=p.name;project.append(option);}project.value=this.project;section.append(project);project.addEventListener("change",()=>{if(project.value)void this.loadProject(project.value);else{this.file=undefined;this.commit=undefined;this.project="";this.bindings=undefined;this.bindingIntent=undefined;this.render();}});
  if(this.project)button("Обновить репозитории проекта",()=>void this.loadProject(this.project));
  for(const binding of this.bindings?.repositories??[]){text(`${binding.repository_name} · ${binding.provider} · подключение ${binding.connection_id} · версия привязки ${binding.revision}`);button(`Подключить push агента: ${binding.repository_name}`,()=>void this.preparePush(this.project,binding.connection_id,binding.repository_id));const ref=input(`Ветка, тег или SHA: ${binding.repository_name}`);button(`Прочитать коммит: ${binding.repository_name}`,()=>void this.readCommit(this.project,binding.connection_id,binding.repository_id,ref.value));if(this.selected?.connection_id===binding.connection_id&&this.selected.enabled)button(`Отозвать у проекта: ${binding.repository_name}`,()=>void this.prepareBinding(this.project,binding.connection_id,binding.repository_id,binding.repository_name,false));}
  if(this.push){text(`Push агента: ${this.push.name}`,"h3");text("Адрес репозитория для push:");text(this.push.url,"pre");text("Ресурс Mnemos для входа агента:");text(this.push.resource,"pre");text("Подключите CLI к этому ресурсу и используйте адрес push с credential helper Mnemos. Требуется WRITE проекта. Отключение Git-привязки или подключения агента прекращает новые отправки через этот маршрут.");text("Ограничение прямой записи в GitHub/GitLab настраивается отдельно у провайдера.");}
  if(this.commit){const c=this.commit;text(`Коммит ${c.value.sha} · проект ${c.project} · подключение ${c.connection} · репозиторий ${c.value.repository_id}`);text(`Запрошено: ${c.ref} · ${c.value.committed_at}`);text(c.value.message,"pre");text(`Родители: ${c.value.parents.join(", ")||"нет"}`);const path=input("Путь файла в этом коммите");button("Прочитать файл",()=>void this.readFile(path.value));}
  if(this.file){text(`${this.file.path} · ${this.file.commit_sha} · ${this.file.size_bytes} байт · SHA-256 ${this.file.sha256}`);text(this.file.content,"pre");}
  if(this.bindings?.next_cursor)button("Следующие репозитории проекта",()=>void this.loadProject(this.project,this.bindings!.next_cursor!));
  if(this.bindingIntent){text(`${this.bindingIntent.input.enabled?"Разрешить проекту":"Отозвать у проекта"} ${this.bindingIntent.input.repository_name}. Права проекта проверит сервер.`);button("Подтвердить привязку",()=>void this.confirmBinding());button("Отменить привязку",()=>{this.bindingIntent=undefined;this.render();});}
  text("Новая заявка","h3");const name=input("Название подключения"),endpoint=input("Адрес API","url","https://api.github.com");
  const provider=document.createElement("select");provider.setAttribute("aria-label","Провайдер Git");provider.disabled=this.busy;for(const value of ["github","gitlab"]){const option=document.createElement("option");option.value=value;option.textContent=value==="github"?"GitHub":"GitLab";provider.append(option);}section.append(provider);
  provider.addEventListener("change",()=>{endpoint.value=provider.value==="github"?"https://api.github.com":"https://gitlab.com/api/v4";});
  button("Сохранить заявку подключения",()=>void this.save({provider:provider.value as GitSetup["provider"],api_base:endpoint.value,name:name.value}));
  if(this.intents.length)text("Сохранённые заявки","h3");
  for(const entry of this.intents)button(`${entry.completed?"Подтверждено":"Проверить заявку"}: ${entry.setup.name} — ${entry.id}`,()=>{this.intent=entry;this.render();});
  if(this.intent){const entry=this.intent;text(`${entry.setup.name} · ${entry.setup.api_base} · ${entry.id}`);button("Проверить результат заявки",()=>void this.inspect(entry.id));
   if(!entry.completed){text(entry.attempted?"Предыдущая отправка не подтверждена. Сначала проверьте результат. Повтор использует тот же ID заявки.":"Ключ будет отправлен серверу; в журнале панели сохраняется только заявка.");const token=input("Ключ внешнего аккаунта","password");button(entry.attempted?"Повторить эту заявку с ключом":"Отправить ключ и подключить",()=>{const value=token.value;token.value="";void this.submit(entry.id,value,entry.attempted);});}
  }
  if(this.selected){const c=this.selected;text(`${c.name} · ${c.provider} · аккаунт ${c.account_login} (${c.account_id}) · версия ${c.revision}`,"h3");
   button(c.enabled?"Отключить подключение…":"Повторить удаление ключа…",()=>{this.disable={id:c.connection_id,revision:c.enabled?c.revision:c.revision-1};this.render();});
   if(this.disable){text("Отключение прекращает использование этого аккаунта через Mnemos.");button("Подтвердить отключение",()=>void this.confirmDisable());button("Отменить отключение",()=>{this.disable=undefined;this.render();});}
   for(const repo of this.repositories?.repositories??[]){text(`${repo.name} · ID ${repo.id} · ветка ${repo.default_branch||"не указана"}`);if(this.project&&c.enabled)button(`Связать с проектом: ${repo.name}`,()=>void this.prepareBinding(this.project,c.connection_id,repo.id,repo.name,true));}
   if(this.repositories?.next_page)button("Следующие репозитории",()=>void this.open(c.connection_id,this.repositories!.next_page!));
  }
 }
}
