// Договор фрейма приложения Mnemos с хостом: методы подключения человека (ui) и методы оболочки.
// Экраны живут в app-react; прежние DOM-экраны удалены ревизией интерфейса 24.09.2026.
import type {WebDAVManagement} from '../src/webdav-accounts.ts';
import type {ImapManagement} from '../src/imap-types.ts';
import type {CalDAVManagement} from '../src/caldav-types.ts';
import type {CalendarDraftManagement} from '../src/calendar-drafts.ts';
import type {MailDraftManagement} from '../src/mail-drafts.ts';
import type {VoiceManagement} from "../src/voice-management.ts";
import type {TelegramManagement} from '../src/telegram-management.ts';
import type {CorporateTaskManagement} from "../src/corporate-task-creation.ts";
import type {ResourceMapManagement} from "../src/resource-map-creation.ts";
import type {ResourceMapEditManagement} from "../src/resource-map-edits.ts";
import type {TrackerInvitations} from "../src/account-session.ts";
import type {TrackerEditManagement} from "../src/tracker-edits.ts";
import type {TrackerManagement} from "../src/tracker-creation.ts";
import type {TeamDocumentManagement} from "../src/team-document-creation.ts";
import type { MnemosAccountSession, ManagedAgentRequest, ManagedTaskRequest } from "../src/account-session.ts";
import type { RpcTarget, RpcStub } from "capnweb";
import type { WhoAmI, ProjectPage, NodePage, DocumentContent, DraftDocument, DraftState, DraftHead, PublicationResult, PublicationReview, PublicationReviewPage, PublicationPolicy, PolicyDomain, PolicyApproverPage, ProjectSearchPage, NodeHistoryPage } from "../src/mnemos-api.ts";
export interface Management extends WebDAVManagement, ImapManagement, CalDAVManagement, CalendarDraftManagement, MailDraftManagement, RpcTarget, TelegramManagement, VoiceManagement {
 beginInboxUpload: MnemosAccountSession["beginInboxUpload"];
 submitInboxUpload: MnemosAccountSession["submitInboxUpload"];
 inboxStatus: MnemosAccountSession["inboxStatus"];
 inboxAlerts: MnemosAccountSession["inboxAlerts"];
 decideInboxAlert: MnemosAccountSession["decideInboxAlert"];
 replayInboxItem: MnemosAccountSession["replayInboxItem"];
 listPeople: MnemosAccountSession["listPeople"];
 createPerson: MnemosAccountSession["createPerson"];
 listPersonRights: MnemosAccountSession["listPersonRights"];
 grantPersonRight: MnemosAccountSession["grantPersonRight"];
 removePersonRight: MnemosAccountSession["removePersonRight"];
 createProject:MnemosAccountSession["createProject"];
 /** Проект с кодом из перетащенной папки: проект, внутренний репозиторий и первый коммит. */
 createCodeProject:MnemosAccountSession["createCodeProject"];
 setProjectVisibility:MnemosAccountSession["setProjectVisibility"];
 listShareRequests:MnemosAccountSession["listShareRequests"];
 /** «Поделились с вами»: документы других людей, открытые этому человеку. */
 listSharedDocuments:MnemosAccountSession["listSharedDocuments"];
 markSharedDocumentSeen:MnemosAccountSession["markSharedDocumentSeen"];
 decideShareRequest:MnemosAccountSession["decideShareRequest"];
 readProjectSharingSettings:MnemosAccountSession["readProjectSharingSettings"];
 updateProjectSharingSettings:MnemosAccountSession["updateProjectSharingSettings"];
 listOrgUnits:MnemosAccountSession["listOrgUnits"];
 createOrgUnit:MnemosAccountSession["createOrgUnit"];
 setOrgUnitMember:MnemosAccountSession["setOrgUnitMember"];
 deleteOrgUnit:MnemosAccountSession["deleteOrgUnit"];
 listInvitations:MnemosAccountSession["listInvitations"];
 /** Ссылку собирает подключение: код приглашения во фрейм отдельно не попадает. */
 createInvitation(email:string,displayName:string,orgUnit:string,role?:import("../src/mnemos-api.ts").InvitationRole,codeAgent?:boolean):Promise<{invitation:import("../src/mnemos-api.ts").OrganizationInvitation;link:string}>;
 revokeInvitation:MnemosAccountSession["revokeInvitation"];
 readWorkshopAgentScope:MnemosAccountSession["readWorkshopAgentScope"];
 updateWorkshopAgentScope:MnemosAccountSession["updateWorkshopAgentScope"];
 readCalendarConnection:MnemosAccountSession["readCalendarConnection"];
 readCalendarEvents:MnemosAccountSession["readCalendarEvents"];
 listCalendarConnections:MnemosAccountSession["listCalendarConnections"];
 readMailMessages:MnemosAccountSession["readMailMessages"];
 listMailConnections:MnemosAccountSession["listMailConnections"];
 readMailConnection:MnemosAccountSession["readMailConnection"];
 uploadUsage:MnemosAccountSession["uploadUsage"];
 prepareCentroid:MnemosAccountSession["prepareCentroid"];
 executeCentroid:MnemosAccountSession["executeCentroid"];
 readReindexBatch:MnemosAccountSession["readReindexBatch"];
 prepareReindexBatch:MnemosAccountSession["prepareReindexBatch"];
 executeReindexBatch:MnemosAccountSession["executeReindexBatch"];
 prepareReindex:MnemosAccountSession["prepareReindex"];
 executeReindex:MnemosAccountSession["executeReindex"];
 policyAlerts:MnemosAccountSession["policyAlerts"];
 reviewPolicyAlert:MnemosAccountSession["reviewPolicyAlert"];
 platformSignalInbox:MnemosAccountSession["platformSignalInbox"];
 readPlatformSignalNotification:MnemosAccountSession["readPlatformSignalNotification"];
 listPlatformSignalOwners:MnemosAccountSession["listPlatformSignalOwners"];
 setPlatformSignalOwner:MnemosAccountSession["setPlatformSignalOwner"];
 listOrganizationRoles:MnemosAccountSession["listOrganizationRoles"];
 createOrganizationRole:MnemosAccountSession["createOrganizationRole"];
 readPrincipalMembership:MnemosAccountSession["readPrincipalMembership"];
 setPrincipalMembership:MnemosAccountSession["setPrincipalMembership"];
 readCalendarGrantState:MnemosAccountSession["readCalendarGrantState"];
 readMailGrantState:MnemosAccountSession["readMailGrantState"];
 setCalendarReadGrant:MnemosAccountSession["setCalendarReadGrant"];
 setMailReadGrant:MnemosAccountSession["setMailReadGrant"];
 disableCalendarConnection:MnemosAccountSession["disableCalendarConnection"];
 disableMailConnection:MnemosAccountSession["disableMailConnection"];
 prepareCorporateAttachment:CorporateTaskManagement["prepareCorporateAttachment"];
 prepareCorporateUpdate:CorporateTaskManagement["prepareCorporateUpdate"];
 executeCorporateUpdate:CorporateTaskManagement["executeCorporateUpdate"];
 recoverCorporateUpdate:CorporateTaskManagement["recoverCorporateUpdate"];
 readCorporateOrigin:MnemosAccountSession["readCorporateOrigin"];
 prepareSharedCorporateWorkflow:CorporateTaskManagement["prepareSharedCorporateWorkflow"];
 executeSharedCorporateWorkflow:CorporateTaskManagement["executeSharedCorporateWorkflow"];
 previewCorporateWorkflow:MnemosAccountSession["previewCorporateWorkflow"];
 readJiraLinks:MnemosAccountSession["readJiraLinks"];
 resolveCorporateTarget:MnemosAccountSession["resolveCorporateTarget"];
 prepareCorporateTask:CorporateTaskManagement["prepareCorporateTask"];
 prepareMappedCorporateTask:CorporateTaskManagement["prepareMappedCorporateTask"];
 prepareMappedJiraCorporateTask:CorporateTaskManagement["prepareMappedJiraCorporateTask"];
 readCorporateCard:CorporateTaskManagement["readCorporateCard"];
 resolveCorporateCardLink:CorporateTaskManagement["resolveCorporateCardLink"];
 saveCorporateCard:CorporateTaskManagement["saveCorporateCard"];
 prepareCorporateRecord:CorporateTaskManagement["prepareCorporateRecord"];
 executeCorporateTask:CorporateTaskManagement["executeCorporateTask"];
  previewJiraImport:MnemosAccountSession["previewJiraImport"];
  resolveBitrixRecordUpdate:MnemosAccountSession["resolveBitrixRecordUpdate"];
  previewBitrixRecordUpdate:MnemosAccountSession["previewBitrixRecordUpdate"];
  previewBitrixDepartmentMembership:MnemosAccountSession["previewBitrixDepartmentMembership"];
  applyBitrixDepartmentMembership:MnemosAccountSession["applyBitrixDepartmentMembership"];
  previewBitrixImport:MnemosAccountSession["previewBitrixImport"];
  listPrivateDraftParticipants:MnemosAccountSession["listPrivateDraftParticipants"];
  setPrivateDraftParticipant:MnemosAccountSession["setPrivateDraftParticipant"];
  prepareTrackedAgentTask:MnemosAccountSession["prepareTrackedAgentTask"];
  resolveDraftConflict:MnemosAccountSession["resolveDraftConflict"];
  listInvitedTrackers:TrackerInvitations["listInvitedTrackers"];
  connectInvitedTracker:TrackerInvitations["connectInvitedTracker"];
  readResourceMapCreation:ResourceMapManagement["readResourceMapCreation"];
  saveResourceMapCreation:ResourceMapManagement["saveResourceMapCreation"];
  executeResourceMapCreation:ResourceMapManagement["executeResourceMapCreation"];
  readResourceMapEdit:ResourceMapEditManagement["readResourceMapEdit"];
  prepareResourceMapEdit:ResourceMapEditManagement["prepareResourceMapEdit"];
  claimResourceMapEdit:ResourceMapEditManagement["claimResourceMapEdit"];
  clearResourceMapEdit:ResourceMapEditManagement["clearResourceMapEdit"];
  readTrackerEdit:TrackerEditManagement["readTrackerEdit"];
  prepareTrackerEdit:TrackerEditManagement["prepareTrackerEdit"];
  claimTrackerEdit:TrackerEditManagement["claimTrackerEdit"];
  clearTrackerEdit:TrackerEditManagement["clearTrackerEdit"];
  readTrackerCreation:TrackerManagement["readTrackerCreation"];
  saveTrackerCreation:TrackerManagement["saveTrackerCreation"];
  executeTrackerCreation:TrackerManagement["executeTrackerCreation"];
 readTemplateProposalBaseline:MnemosAccountSession["readTemplateProposalBaseline"];
 readTemplateProposalSource:MnemosAccountSession["readTemplateProposalSource"];
 readSavedTemplateDecision:MnemosAccountSession["readSavedTemplateDecision"];
 saveTemplateDecision:MnemosAccountSession["saveTemplateDecision"];
 executeSavedTemplateDecision:MnemosAccountSession["executeSavedTemplateDecision"];
 resolveWorkTemplate:MnemosAccountSession["resolveWorkTemplate"];
 listManagedTemplateScopes:MnemosAccountSession["listManagedTemplateScopes"];
 setTemplateScope:MnemosAccountSession["setTemplateScope"];
 listTemplateReviewScopes:MnemosAccountSession["listTemplateReviewScopes"];
 listTemplateProposals:MnemosAccountSession["listTemplateProposals"];
 readTemplateProposal:MnemosAccountSession["readTemplateProposal"];
 listTemplateScopes: MnemosAccountSession["listTemplateScopes"];
 listScopedWorkTemplates: MnemosAccountSession["listScopedWorkTemplates"];
 readScopedWorkTemplate: MnemosAccountSession["readScopedWorkTemplate"];
 listWorkTemplates: MnemosAccountSession["listWorkTemplates"];
 readWorkTemplate: MnemosAccountSession["readWorkTemplate"];
 readSavedTemplateAction: MnemosAccountSession["readSavedTemplateAction"];
 saveTemplateAction: MnemosAccountSession["saveTemplateAction"];
 deferTemplateAction: MnemosAccountSession["deferTemplateAction"];
 restoreTemplateAction: MnemosAccountSession["restoreTemplateAction"];
 executeSavedTemplateAction: MnemosAccountSession["executeSavedTemplateAction"];
 readSavedAbsenceAction: MnemosAccountSession["readSavedAbsenceAction"];
 saveAbsenceAction: MnemosAccountSession["saveAbsenceAction"];
 executeSavedAbsenceAction: MnemosAccountSession["executeSavedAbsenceAction"];
 createAbsenceTask: MnemosAccountSession["createAbsenceTask"];
 readAbsenceTask: MnemosAccountSession["readAbsenceTask"];
 dispatchAbsenceTask: MnemosAccountSession["dispatchAbsenceTask"];
 cancelAbsenceTask: MnemosAccountSession["cancelAbsenceTask"];
 readAbsenceRuntime: MnemosAccountSession["readAbsenceRuntime"];

 readAgentAbsence: MnemosAccountSession["readAgentAbsence"];
 setAgentAbsence: MnemosAccountSession["setAgentAbsence"];
 deferBudgetDraft: MnemosAccountSession["deferBudgetDraft"];
 resumeBudgetDraft: MnemosAccountSession["resumeBudgetDraft"];
 cancelSavedTeamTask: MnemosAccountSession["cancelSavedTeamTask"];
 budgetSavedAgentTask: MnemosAccountSession["budgetSavedAgentTask"];
 prepareTeamBudgetRework: MnemosAccountSession["prepareTeamBudgetRework"];
 prepareTeamBudgetReview: MnemosAccountSession["prepareTeamBudgetReview"];
 readTeamResultDraft: TeamDocumentManagement["readTeamResultDraft"];
 createTeamResultDocument: TeamDocumentManagement["createTeamResultDocument"];
 readTeamResultContribution: MnemosAccountSession["readTeamResultContribution"];
 recordTeamResultContribution: MnemosAccountSession["recordTeamResultContribution"];
 readTeamResultReview: MnemosAccountSession["readTeamResultReview"];
 readTeamMemberObservation: MnemosAccountSession["readTeamMemberObservation"];
 readTeamMemberActivity: MnemosAccountSession["readTeamMemberActivity"];
 readTeamBudgetUsage: MnemosAccountSession["readTeamBudgetUsage"];
 runTeamBudgetMember: MnemosAccountSession["runTeamBudgetMember"];
 readTeamBudgetMember: MnemosAccountSession["readTeamBudgetMember"];
 readTeamMemberInputs: MnemosAccountSession["readTeamMemberInputs"];
 cancelTeamBudgetMember: MnemosAccountSession["cancelTeamBudgetMember"];

 listTeamBudgets: MnemosAccountSession["listTeamBudgets"];
 readTeamBudget: MnemosAccountSession["readTeamBudget"];
 createTeamBudget: MnemosAccountSession["createTeamBudget"];
 decideTeamBudget: MnemosAccountSession["decideTeamBudget"];
 saveProjectSignalAssessment: MnemosAccountSession["saveProjectSignalAssessment"];
 readPublishedProjectSignals: MnemosAccountSession["readPublishedProjectSignals"];
 publishProjectSignals: MnemosAccountSession["publishProjectSignals"];
 readProjectSignalAssessment: MnemosAccountSession["readProjectSignalAssessment"];
 assessProjectSignals: MnemosAccountSession["assessProjectSignals"];
 listBudgetProjects: MnemosAccountSession["listBudgetProjects"];
  readProjectBudget: MnemosAccountSession["readProjectBudget"];
  readSpending: MnemosAccountSession["readSpending"];
  setProjectBudget: MnemosAccountSession["setProjectBudget"];

 finishedAgentTasks: MnemosAccountSession["finishedAgentTasks"];
 readFinishedAgentTask: MnemosAccountSession["readFinishedAgentTask"];
 prepareAgentRework: MnemosAccountSession["prepareAgentRework"];

  readCollaborationProgress: MnemosAccountSession["readCollaborationProgress"];
  reviewCollaborationResult: MnemosAccountSession["reviewCollaborationResult"];

  listCollaborations: MnemosAccountSession["listCollaborations"];
  readCollaboration: MnemosAccountSession["readCollaboration"];
  createCollaboration: MnemosAccountSession["createCollaboration"];
  listCollaborationMessages: MnemosAccountSession["listCollaborationMessages"];
  appendCollaborationMessage: MnemosAccountSession["appendCollaborationMessage"];

  listEngagementRules: MnemosAccountSession["listEngagementRules"];
  setEngagementRule: MnemosAccountSession["setEngagementRule"];
  readPersonalMemory: MnemosAccountSession["readPersonalMemory"];
  readPersonalMemoryVersion: MnemosAccountSession["readPersonalMemoryVersion"];
  setPersonalMemory: MnemosAccountSession["setPersonalMemory"];
  listPrivateDocuments: MnemosAccountSession["listPrivateDocuments"];
  listPrivateDocumentsForOwner: MnemosAccountSession["listPrivateDocumentsForOwner"];
  recordUIReadiness: MnemosAccountSession["recordUIReadiness"];
  readPlatformMetrics: MnemosAccountSession["readPlatformMetrics"];
  managedTaskRequest(): Promise<ManagedTaskRequest | null>;
  discardUnsentAgentTask: MnemosAccountSession["discardUnsentAgentTask"];
  reviewSavedAgentTask: MnemosAccountSession["reviewSavedAgentTask"];
  prepareAgentTask: MnemosAccountSession["prepareAgentTask"];
  submitSavedAgentTask(id: string): Promise<ManagedTaskRequest>;
  refreshSavedAgentTask(id: string): Promise<ManagedTaskRequest>;
  finishSavedAgentTask(id: string): Promise<void>;
  managedAgentRequest(): Promise<ManagedAgentRequest | null>;
  prepareManagedAgent(template: string): Promise<ManagedAgentRequest>;
  submitManagedAgent(id: string): Promise<ManagedAgentRequest>;
  finishManagedAgentRequest(id: string): Promise<void>;
  openDraft(project: string): Promise<DraftHead>;
  readDraftDocument(project: string, node: string): Promise<DraftDocument>;
  draftState(project: string): Promise<DraftState>;
  readPublishedHead: MnemosAccountSession["readPublishedHead"];
  readPrivateVersionDigest: MnemosAccountSession["readPrivateVersionDigest"];
  saveDraftDocument(project: string, node: string, upload: string, head: string): Promise<DraftHead>;
  listPublicationReviews(cursor: string): Promise<PublicationReviewPage>;
  recordReviewDecision(id: string, domain: string, version: number, approved: boolean): Promise<void>;
  readPublicationPolicy(project: string): Promise<PublicationPolicy>;
  listPolicyApprovers(project: string, cursor: string): Promise<PolicyApproverPage>;
  setPublicationPolicy(project: string, revision: number, domains: PolicyDomain[]): Promise<{ revision: number }>;
  readPublicationReview(id: string): Promise<PublicationReview>;
  requestPublicationReview(project: string, personal: string, shared: string): Promise<{ candidate_id: string }>;
  publishDraft(project: string, head: string, shared: string, message: string): Promise<PublicationResult>;
  browseProject(project: string, cursor: string): Promise<NodePage>;
  readProjectDocument(project: string, node: string): Promise<DocumentContent>;
  searchProject(project: string, query: string): Promise<ProjectSearchPage>;
  nodeHistory(project: string, node: string, cursor: string): Promise<NodeHistoryPage>;
  /** Public setup parameters for connecting an external CLI to this organization. */
  /** Explicitly grant or remove one agent's project permission. */
  setAgentProjectRight: MnemosAccountSession["setAgentProjectRight"];
  externalAgentSetup: MnemosAccountSession["externalAgentSetup"];
  whoAmI(): Promise<WhoAmI>;
  listProjects(): Promise<ProjectPage>;
  listVisibleDatabaseConnections:MnemosAccountSession["listVisibleDatabaseConnections"];
  listDatabaseConnections:MnemosAccountSession["listDatabaseConnections"];
  registerDatabaseConnection:MnemosAccountSession["registerDatabaseConnection"];
  removeDatabaseConnection:MnemosAccountSession["removeDatabaseConnection"];
  readOperationAudit:MnemosAccountSession["readOperationAudit"];
  readOperationAuditPage:MnemosAccountSession["readOperationAuditPage"];
  listWorkJournal:MnemosAccountSession["listWorkJournal"];
  readGitFile:MnemosAccountSession["readGitFile"];
  readGitCommit:MnemosAccountSession["readGitCommit"];
  readGitTree:MnemosAccountSession["readGitTree"];
  listGitBranches:MnemosAccountSession["listGitBranches"];
  readGitLog:MnemosAccountSession["readGitLog"];
  compareGitRefs:MnemosAccountSession["compareGitRefs"];
  readProjectOverview:MnemosAccountSession["readProjectOverview"];
  workspaceAvailable():Promise<boolean>;
  listWorkspaceTasks(project:string):Promise<{tasks:import("../src/workspace-tasks.ts").WorkspaceTaskView[]}>;
  startWorkspaceTask(project:string,connection:string,repository:string,prompt:string):Promise<import("../src/workspace-tasks.ts").WorkspaceTaskView>;
  readWorkspaceTask(project:string,task:string):Promise<import("../src/workspace-tasks.ts").WorkspaceTaskDetails>;
  messageWorkspaceTask(project:string,task:string,text:string):Promise<void>;
  abortWorkspaceTask(project:string,task:string):Promise<void>;
  readOwnedGitBinding:MnemosAccountSession["readOwnedGitBinding"];
  listProjectGitRepositories: MnemosAccountSession["listProjectGitRepositories"];
  bindGitRepository: MnemosAccountSession["bindGitRepository"];
  listGitConnections: MnemosAccountSession["listGitConnections"];
  readGitConnection: MnemosAccountSession["readGitConnection"];
  disableGitConnection: MnemosAccountSession["disableGitConnection"];
  listGitRepositories: MnemosAccountSession["listGitRepositories"];
  listGitSyncLinks: MnemosAccountSession["listGitSyncLinks"];
  listProjectGitSync: MnemosAccountSession["listProjectGitSync"];
  createGitSyncLink: MnemosAccountSession["createGitSyncLink"];
  updateGitSyncLink: MnemosAccountSession["updateGitSyncLink"];
  deleteGitSyncLink: MnemosAccountSession["deleteGitSyncLink"];
  refreshGitSyncLink: MnemosAccountSession["refreshGitSyncLink"];
  listGitAppRepositories: MnemosAccountSession["listGitAppRepositories"];
  startGitHubConnect: MnemosAccountSession["startGitHubConnect"];
  listGitHubAccounts: MnemosAccountSession["listGitHubAccounts"];
  disconnectGitHubAccount: MnemosAccountSession["disconnectGitHubAccount"];
  listGitRegistrationIntents: MnemosAccountSession["listGitRegistrationIntents"];
  saveGitRegistrationIntent: MnemosAccountSession["saveGitRegistrationIntent"];
  inspectGitRegistrationIntent: MnemosAccountSession["inspectGitRegistrationIntent"];
  executeGitRegistrationIntent: MnemosAccountSession["executeGitRegistrationIntent"];
  listAgentConnections: MnemosAccountSession["listAgentConnections"];
  checkTrackerAssignee: MnemosAccountSession["checkTrackerAssignee"];
  revokeAgentConnection(id: string): Promise<void>;
}
export interface Host extends RpcTarget {
  openTemplateProposal(project:string,node:string,proposal:string):Promise<void>;
  openNativeDocument(project: string, resource: string): Promise<boolean>;
  openPrompt(prompt: string, project?:{projectId:string;title:string}): void;
  setUnsavedChanges(dirty: boolean): void;
  subscribeAccent(frame: RpcTarget): string;
  getSelectedSection(): string;
  /** Представление рядом с беседой без изменения прав. */
  getPresentationMode(): Promise<string>;
  pickInboxFiles(directory: boolean, project?: string): Promise<import("../src/intake.ts").PickedIntakeFile[]>;
  openSection(section: string, project?: string): void;
  openApprovals(): Promise<void>;
  getSelectedProject(): Promise<string>;
  /** Вкладка раздела из адреса хоста; пусто — вкладка по умолчанию. */
  getSelectedView(): Promise<string>;
  /** Документ из адреса хоста (ссылка из письма «поделились с вами»); пусто — не задан. Прав не даёт. */
  getSelectedDocument(): Promise<string>;
  /** Записывает вкладку в адрес без перезагрузки фрейма. */
  selectView(view: string): void;
  saveMailAttachment(bytes:Uint8Array,filename:string):Promise<void>;
  createCalendarDraft(id:string,sha256:string):Promise<import('@gadgets/workshop-shared/calendar-draft').CalendarDraftExecution>;
  sendMailDraft(id:string,sha256:string):Promise<{state:'attempted'|'accepted';message_id?:string}>;
  uploadText(project: string, text: string): Promise<string>;
  downloadReviewText(review: string, node: string, version: number, side: "before" | "after"): Promise<string | null>;
  downloadFile(project:string,node:string,version:string,filename:string):Promise<void>;
  downloadText(project: string, node: string, head: string, side: number): Promise<string>;
  ui: RpcStub<Management>; subscribeTheme(frame: RpcTarget): Promise<string>;
  /** Открывает страницу установки или настроек приложения GitHub в новой вкладке; false — не открылась. */
  openGitHubAppPage(url: string): Promise<boolean>;
  /** Итог возврата с GitHub (?github=…), отдаётся один раз; null — возврата не было. */
  takeGitHubReturn(): Promise<{ result: "connected" | "updated" | "failed"; reason: string } | null> }
